using System.Collections.Generic;
using static LoreMaster.ItemChangerData.Other.LocationList;

namespace LoreMaster.ItemChangerData.Other;

internal static class PinLocations
{
    internal static Dictionary<string, (float, float, string, string)> Locations { get; set; } = new()
    {
        { Gorb_Grave, (-0.9f, 1.1f, "Gorb", null) },
        { Gravedigger, (1.2f, -0.4f, "Gravedigger", null) }, 
        { Tiso_Dirtmouth, (0.8f, .5f, "Tiso", null)}, 
        { Tiso_Crossroads, (0.3f, 0f, "Tiso", null) },
        { Tiso_Blue_Lake, (-1.9f, -0.1f, "Tiso", null) },
        { Myla, (0.3f, -0.3f, "Myla", null) },
        { Quirrel_Crossroads, (0.2f, -.1f, "Quirrel", "Crossroads_02") },
        { Aspid_Queen_Dream, (0.4f, 0f, "Dream_Nail", null) },
        { No_Eyes_Statue, (0.7f, -.4f, "No_Eyes", "Fungus1_34") },
        { Quirrel_Greenpath, (0.2f, .2f, "Quirrel", "Fungus1_26") },
        { Zote_Greenpath, (-0.5f, 0f, "Zote", null) },
        { Zote_Dirtmouth_Intro, (0.3f, 0.5f, "Zote", null) },
        { Overgrown_Shaman_Dream, (-.7f, -.1f, "Dream_Nail", "Fungus3_44") },
        { Quirrel_Queen_Station, (-0.3f, 0.1f, "Quirrel", null) },
        { Quirrel_Mantis_Village, (0.5f, -0.1f, "Quirrel", null) },
        { Shroom_King_Dream, (0.3f, -0.8f, "Dream_Nail", null) },
        { Elder_Hu_Grave, (0.2f, -0.2f, "Elder_Hu", null) }, 
        { Dashmaster_Statue_Dream, (-0.3f, -0.6f, "Dream_Nail", null) },
        { Quirrel_City, (0.4f, -0.4f, "Quirrel", null) },
        { City_Fountain, (-0.2f, -0.5f, "Lore", null) },
        { Zote_City, (0.3f, 0f, "Zote", null) },
        { Marissa, (0.2f, -0.3f, "Marissa", null) },
        { Poggy, (0.4f, 0.6f, "Poggy", null) },
        { Willoh, (-0.1f, 0f, "Willoh", null) },
        { Fluke_Hermit, (1f, 1f, "Fluke_Hermit", "GG_Waterways") },
        { Dung_Defender, (0.4f, 0f, "Dung_Defender", null) },
        { Isma_Dream, (0.7f, -0.5f, "Dream_Nail", null) },
        { Emilitia, (0f, 0f, "Emilitia", "Ruins2_04") },
        { Beast_Den_Altar, (0.3f, .6f, "Lore", "Deepnest_10") },
        { Midwife, (0.4f, -1f, "Midwife", null) },
        { Weaver_Seal, (1.4f, .3f, "Lore", "Deepnest_39") },
        { Mask_Maker, (-0.3f, -0.1f, "Mask_Maker", null) },
        { Cloth_Fungal_Wastes, (-0.1f, 0f, "Cloth", null) },
        { Cloth_Basin, (-1.2f, 0.2f, "Cloth", null) },
        { Cloth_Deepnest, (0, 0.2f, "Cloth", null) },
        { Zote_Deepnest, (0.2f, -0.1f, "Zote", null) },
        { Grub_Seal, (0.2f, 1.2f, "Lore", null) },
        { Quirrel_Peaks, (-0.5f, -0.1f, "Quirrel", null) },
        { Radiance_Statue_Dream, (-1.3f, 0.5f, "Dream_Nail", null) },
        { Quirrel_Deepnest, (-0.5f, -1.3f, "Quirrel", null) },
        { Quirrel_Outside_Archive, (0.2f, -0.4f, "Quirrel", null) },
        { Quirrel_After_Monomon, (0f, -.4f, "Quirrel", "Fungus3_47") },
        { Quirrel_Blue_Lake, (1.7f, -0.1f, "Quirrel", null) },
        { Mine_Golem_Dream, (1.9f, -0.5f, "Dream_Nail", null) },
        { Crystalized_Shaman_Dream, (0.6f, 0.2f, "Dream_Nail", "Mines_28") },
        { Xero_Grave, (0.8f, 0f, "Xero", null) },
        { Dreamer_Tablet, (0, -0.3f, "Lore", null) },
        { Dream_Shield_Statue_Dream, (-0.2f, 0f, "Dream_Nail", null) },
        { Snail_Shaman_Tomb_Dream, (2.7f, 0f, "Dream_Nail", null) },
        { Galien_Corpse, (-0.5f, -0.3f, "Galien", null) },
        { Shriek_Statue_Dream, (-0.8f, 0f, "Dream_Nail", null) },
        { Shade_Golem_Dream_Normal, (1.2f, 0.1f, "Dream_Nail", null) },
        { Shade_Golem_Dream_Void, (1.5f, 0.1f, "Dream_Nail", null) },
        { Hopper_Dummy_Dream, (0, -0.1f, "Dream_Nail", null) },
        { Ancient_Nailsmith_Golem_Dream, (0.2f, 0.1f, "Dream_Nail", null) },
        { Vespa, (0.5f, 0f, "Vespa", null) },
        { Bardoon, (0f, 1.4f, "Bardoon", null) },
        { Tiso_Colosseum, (0.4f, 1.8f, "Tiso", "Deepnest_East_07") },
        { Zote_Colosseum, (0.1f, 1.8f, "Zote", "Deepnest_East_07") },
        { Tiso_Corpse, (-0.2f, -0.5f, "tiso_corpse", null) },
        { Markoth_Corpse, (0.3f, 0f, "Markoth", null) },
        { Zote_Dirtmouth_After_Colosseum, (0.3f, .2f, "Zote", null) },
        { Marmu_Grave, (-0.3f, 0.1f, "Marmu", null) },
        { Dryya_Dream, (0.1f, 0.7f, "Dream_Nail", null) },
        { Grasshopper, (0.6f, 0f, "Grasshopper", null) },
        { Cloth_Garden, (-1.2f, 0f, "Cloth", null) },
        { Cloth_Ghost, (-0.4f, 0.1f, "Cloth", null) },
        { Cloth_Town, (-.3f, .5f, "Cloth", "Town") },
        { Bretta_Diary, (0f, 0.5f, "Bretta_Diary", "Town") },
        { Menderbug_Diary, (-0.4f, -.1f, "Menderbug_Diary", "Crossroads_04") },
        { Grimm_Summoner_Dream, (0.8f, -0.1f, "Dream_Nail", null) },
        { Grimm_Summoner_Corpse, (0.8f, 0.1f, "Lore", null) },
        { Grimm_Machine, (-.8f, 0.2f, "Lore", "Town") },
        { Joni, (0.4f, -0.5f, "Joni", null) },
        { Moss_Prophet, (0.4f, -0.4f, "Moss_Prophet", null) },
        { Queen, (-0.1f, 1.1f, "Queen", "Fungus3_48") },
        { Garden_Golem, (-0.9f, -0.1f, "Lore", null) },
        { Kings_Mould_Machine_Dream, (0.8f,0.7f, "Dream_Nail", "Abyss_05") },
        { White_Palace_Nursery, (0.5f, 0.7f, "Lore", "Abyss_05") },
        { Pale_King_Dream, (0.2f,0.7f, "Pale_King", "Abyss_05") },
        { Stag_Nest, (-1.7f, 1.3f, "Lore", "Cliffs_02") },
        { $"{Elderbug_Reward_Prefix}1", (-1f, 1.4f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}2", (-0.7f, 1.4f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}3", (-.4f, 1.4f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}4", (-.1f, 1.4f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}5", (.2f, 1.4f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}6", (-1f, 1.1f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}7", (-0.7f, 1.1f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}8", (-.4f, 1.1f, "Elderbug", "Town") },
        { $"{Elderbug_Reward_Prefix}9", (-.1f, 1.1f, "Elderbug", "Town") },
        { Lore_Tablet_Record_Bela, (.4f,-.2f, "Lore", null) },
        { Traitor_Grave, (-.3f,0f, "Lore", null) }
    };
}
