//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TwistedPowerHints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwistedPowerHints() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.TwistedPowerHints", typeof(TwistedPowerHints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you eaten too much shrooms lately? Something feels wrong. It seems like you are occasionly under their effects at least. ähnelt.
        /// </summary>
        internal static string BagOfMushrooms {
            get {
                return ResourceManager.GetString("BagOfMushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t even dare breaking things is this world. If you do, you will pay with your geo... or kneecaps if you don&apos;t have any. ähnelt.
        /// </summary>
        internal static string BestMenderInTheWorld {
            get {
                return ResourceManager.GetString("BestMenderInTheWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your wings seems to have lost their rejuvenation! But hey, as you get older it is normal that some thing take a bit more time. ähnelt.
        /// </summary>
        internal static string BlessingOfTheButterfly {
            get {
                return ResourceManager.GetString("BlessingOfTheButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wow, you camouflaging so well, that not even yourself can see you anymore. ähnelt.
        /// </summary>
        internal static string Camouflage {
            get {
                return ResourceManager.GetString("Camouflage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enviromental Hazards scare you back at the entrance of the room, if you came in contact with them. ähnelt.
        /// </summary>
        internal static string CaringShell {
            get {
                return ResourceManager.GetString("CaringShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taking damage does shake your head up ahead. It might take a few seconds before the concussion on you end. Don&apos;t try to walk! ähnelt.
        /// </summary>
        internal static string ConcussiveStrike {
            get {
                return ResourceManager.GetString("ConcussiveStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poggy loves rancid eggs! You should share yours with him, before he eventually succumb to his hunger and decides to eat you instead. ähnelt.
        /// </summary>
        internal static string DeliciousMeal {
            get {
                return ResourceManager.GetString("DeliciousMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The crystal heart is overloaded, making you unstoppable... even for yourself unfortunately. A friendly hit or wall are your only escape options. ähnelt.
        /// </summary>
        internal static string DiamondCore {
            get {
                return ResourceManager.GetString("DiamondCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The vessel of the crystal heart takes more time to gather enough energy. ähnelt.
        /// </summary>
        internal static string DiamondDash {
            get {
                return ResourceManager.GetString("DiamondDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wearing charms will be a bit more expensive. Damn inflation... ähnelt.
        /// </summary>
        internal static string DiminishingCurse {
            get {
                return ResourceManager.GetString("DiminishingCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your knees shiver in fear, once you enter a fight against a stronger foe. ähnelt.
        /// </summary>
        internal static string DramaticEntrance {
            get {
                return ResourceManager.GetString("DramaticEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Casting the ancient moth artifact might take more time. Maybe defeating the dreamers may help you with that? ähnelt.
        /// </summary>
        internal static string DreamBlessing {
            get {
                return ResourceManager.GetString("DreamBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When entering a new room with enemies the list marks enemies. If you succeed the \&quot;talk\&quot; with them, you are granted a reward. Be careful, elderbug demands a clean execution. ähnelt.
        /// </summary>
        internal static string ElderbugHitList {
            get {
                return ResourceManager.GetString("ElderbugHitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you considered taking a shower? You stink a bit. The clouds that follow you are visible and making it harder to see! ähnelt.
        /// </summary>
        internal static string EternalSentinel {
            get {
                return ResourceManager.GetString("EternalSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting a battle and leaving it, without finishing your opponent off, will mark you as a coward and so you will be punished. ähnelt.
        /// </summary>
        internal static string EternalValor {
            get {
                return ResourceManager.GetString("EternalValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Without the sharp eye of the watcher it feels a bit darker than usual... ähnelt.
        /// </summary>
        internal static string EyeOfTheWatcher {
            get {
                return ResourceManager.GetString("EyeOfTheWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The only way energy can thrive through your nail is with some kind of flower in your pocket. ähnelt.
        /// </summary>
        internal static string FlowerRing {
            get {
                return ResourceManager.GetString("FlowerRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The dream nail is unstable and can only be used if you sacrify some essence. ähnelt.
        /// </summary>
        internal static string FollowTheLight {
            get {
                return ResourceManager.GetString("FollowTheLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I thought those jellyfishs are only in Fog Canyon. BUT THEIR ARE EVERYWHERE! ähnelt.
        /// </summary>
        internal static string FriendOfTheJellyfish {
            get {
                return ResourceManager.GetString("FriendOfTheJellyfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Without Unn&apos;s blessing, focusing might take more out of you, than you would like. ähnelt.
        /// </summary>
        internal static string GiftOfUnn {
            get {
                return ResourceManager.GetString("GiftOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every foe on your right is as poor as you could imagine. ähnelt.
        /// </summary>
        internal static string GloryOfTheWealth {
            get {
                return ResourceManager.GetString("GloryOfTheWealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your feet create a wonderful flora! That flesh eating plants are a part of this, was not communicated, tho... ähnelt.
        /// </summary>
        internal static string GraspOfLife {
            get {
                return ResourceManager.GetString("GraspOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jumping around may shuffle your pocket a bit around and accidently throwing a bomb on the ground. Be careful to not blow yourself up. ähnelt.
        /// </summary>
        internal static string GrassBombardement {
            get {
                return ResourceManager.GetString("GrassBombardement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On death not only shall break your shell but also the last piece of knowledge that you acquired. ähnelt.
        /// </summary>
        internal static string GreaterMind {
            get {
                return ResourceManager.GetString("GreaterMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting hit, makes you more and more sad, eventually killing the happy adventurer in you. Without the motivation, you don&apos;t even try to proceed normally! Maybe a break on a bench may increase your mood. ähnelt.
        /// </summary>
        internal static string HappyFate {
            get {
                return ResourceManager.GetString("HappyFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While your nail is cold, it will only poke your opponent. Don&apos;t let the heat of your nail go away! Keep hitting them, heating up the battle to actually hurt them. ähnelt.
        /// </summary>
        internal static string HotStreak {
            get {
                return ResourceManager.GetString("HotStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sometimes you focus on the wrong things... ähnelt.
        /// </summary>
        internal static string Imposter {
            get {
                return ResourceManager.GetString("Imposter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WHY ARE THERE SPIDERS EVERYWHERE, AHHHH! ähnelt.
        /// </summary>
        internal static string Infested {
            get {
                return ResourceManager.GetString("Infested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You feeling heavy like a stone, stomping in the ground on almost every jump. ähnelt.
        /// </summary>
        internal static string JellyBelly {
            get {
                return ResourceManager.GetString("JellyBelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really swim in water? It doesn&apos;t seem like you&apos;re moving at all... ähnelt.
        /// </summary>
        internal static string JellyfishFlow {
            get {
                return ResourceManager.GetString("JellyfishFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Since the Pale King called those, who work with lifeblood heretics, you also abstain from using it. Just like a good kid. ähnelt.
        /// </summary>
        internal static string JonisProtection {
            get {
                return ResourceManager.GetString("JonisProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why are your steps so loud? Some foes might be getting alarmed early about your arrival. ähnelt.
        /// </summary>
        internal static string LaughableThreat {
            get {
                return ResourceManager.GetString("LaughableThreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sometimes you will be haunted by a ghost from a distant land. They will block most entrances until you kill them. ähnelt.
        /// </summary>
        internal static string LifebloodOmen {
            get {
                return ResourceManager.GetString("LifebloodOmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your nail has broken into two pieces, making it &quot;slighly&quot; shorter. ähnelt.
        /// </summary>
        internal static string MantisStyle {
            get {
                return ResourceManager.GetString("MantisStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why can&apos;t people just enjoy good music? No, of course that is not possible. You will be haunted by Marissas biggest fan. ähnelt.
        /// </summary>
        internal static string MarissasAudience {
            get {
                return ResourceManager.GetString("MarissasAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trusting in the wrong masks, slowly drains all soul from you. ähnelt.
        /// </summary>
        internal static string MaskOvercharge {
            get {
                return ResourceManager.GetString("MaskOvercharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All enemies bodies are invincible. Reading there dreams may show your their weakness. If you haven&apos;t acquired the dream artifact, all enemies are way tougher instead. ähnelt.
        /// </summary>
        internal static string MindblastOfUnn {
            get {
                return ResourceManager.GetString("MindblastOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occasionally you emit a spore cloud. Don&apos;t breathe the pollen in too much. ähnelt.
        /// </summary>
        internal static string OneOfUs {
            get {
                return ResourceManager.GetString("OneOfUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Casting spells with full capacity will grant your spell the powers they need to actually hurting your foes. ähnelt.
        /// </summary>
        internal static string OverwhelmingPower {
            get {
                return ResourceManager.GetString("OverwhelmingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Victims hitten by your nail are sometimes blessed by the pale king and heal themselves instead. ähnelt.
        /// </summary>
        internal static string PaleLuck {
            get {
                return ResourceManager.GetString("PaleLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Casting a spell takes every last bit of your soul. ähnelt.
        /// </summary>
        internal static string PureSpirit {
            get {
                return ResourceManager.GetString("PureSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You feel how thorns want to rip out of your body... ähnelt.
        /// </summary>
        internal static string QueenThorns {
            get {
                return ResourceManager.GetString("QueenThorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The flukes have eaten your vengeful spirits. But only a few of them actually survived long enough. ähnelt.
        /// </summary>
        internal static string RelentlessSwarm {
            get {
                return ResourceManager.GetString("RelentlessSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While you don&apos;t stay on the path, your nail force will be lowered significant. ähnelt.
        /// </summary>
        internal static string ReluctantPilgrim {
            get {
                return ResourceManager.GetString("ReluctantPilgrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your spirit will always be called to the graveyard. ähnelt.
        /// </summary>
        internal static string Requiem {
            get {
                return ResourceManager.GetString("Requiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are slowly dragged to Unn. ähnelt.
        /// </summary>
        internal static string ReturnToUnn {
            get {
                return ResourceManager.GetString("ReturnToUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your shell is very fragile, causing all hits on it, to be more devistating. ähnelt.
        /// </summary>
        internal static string SacredShell {
            get {
                return ResourceManager.GetString("SacredShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You now enforced by the rule of physics... or biology? Anyway, the more damaged you are, the less power is behind your strikes. ähnelt.
        /// </summary>
        internal static string ScrewTheRules {
            get {
                return ResourceManager.GetString("ScrewTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The void energy may take a little bit longer to return to you. ähnelt.
        /// </summary>
        internal static string ShadowForged {
            get {
                return ResourceManager.GetString("ShadowForged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All of your charms are stripped by their powers! ähnelt.
        /// </summary>
        internal static string ShiningBound {
            get {
                return ResourceManager.GetString("ShiningBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gathering soul is a lot harder. Your soul vessels are slowly leaking as well. ähnelt.
        /// </summary>
        internal static string SoulExtractEfficiency {
            get {
                return ResourceManager.GetString("SoulExtractEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The old stag seems to have Alzheimer and forget to which station he should actually travel. ähnelt.
        /// </summary>
        internal static string StagAdoption {
            get {
                return ResourceManager.GetString("StagAdoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The grass may expand onto your life force if you stand too long close to it. ähnelt.
        /// </summary>
        internal static string TouchGrass {
            get {
                return ResourceManager.GetString("TouchGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entering the black egg now requires a heavy fee. ähnelt.
        /// </summary>
        internal static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lemm got a little bit stingy. ähnelt.
        /// </summary>
        internal static string TreasureHunter {
            get {
                return ResourceManager.GetString("TreasureHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your true form may slip out of your vessel from time to time trying to flee... with all your geo. ähnelt.
        /// </summary>
        internal static string TrueForm {
            get {
                return ResourceManager.GetString("TrueForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your companions are jealous of eachother, not focusing on what they should do. ähnelt.
        /// </summary>
        internal static string UnitedWeStand {
            get {
                return ResourceManager.GetString("UnitedWeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It&apos;s hard to not talk about a shade, when EVERYONE has one. ähnelt.
        /// </summary>
        internal static string WeDontTalkAboutShade {
            get {
                return ResourceManager.GetString("WeDontTalkAboutShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gaining a pure focus may took longer. ähnelt.
        /// </summary>
        internal static string WellFocused {
            get {
                return ResourceManager.GetString("WellFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Without the help of the sage, handling spells might be a little bit inefficient. ähnelt.
        /// </summary>
        internal static string WisdomOfTheSage {
            get {
                return ResourceManager.GetString("WisdomOfTheSage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You became a hive, spawning hatchlings from time to time. But these once have quite an appetite for soul. ähnelt.
        /// </summary>
        internal static string YouLikeJazz {
            get {
                return ResourceManager.GetString("YouLikeJazz", resourceCulture);
            }
        }
    }
}
