//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdditionalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdditionalText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.AdditionalText", typeof(AdditionalText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br&gt;The vessel of the core is forged with a powerful diamond plate. You promised that you give it back to Myla... right? ähnelt.
        /// </summary>
        internal static string CORELESS_DIAMOND_HEART_DESCRIPTION {
            get {
                return ResourceManager.GetString("CORELESS_DIAMOND_HEART_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diamond Heart (Shell) ähnelt.
        /// </summary>
        internal static string CORELESS_DIAMOND_HEART_NAME {
            get {
                return ResourceManager.GetString("CORELESS_DIAMOND_HEART_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This town may not hold the most interesting wisdom, but the kingdom below sure does. There a plenty of tablets and creatures which you can learn from. Maybe someday, I&apos;ll be able to call you &quot;Lore Master&quot;. Oh what a thought, excuse me. Anyway, if you want to explore the world below, keeping track of every knowledge that you acquired might be hard. Let me help you with that. This is a relic which tracks every bit of information that you&apos;ve collected so far. Sometimes, the knowledge can be more of a threat th [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ELDERBUG_INTRO_MAIN {
            get {
                return ResourceManager.GetString("ELDERBUG_INTRO_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br&gt;Bathed and reforged with powerful diamonds. Formerly in possession of the crystal leader, this artefact can cause massive earth quakes. ähnelt.
        /// </summary>
        internal static string FULL_DIAMOND_HEART_DESCRIPTION {
            get {
                return ResourceManager.GetString("FULL_DIAMOND_HEART_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diamond Heart ähnelt.
        /// </summary>
        internal static string FULL_DIAMOND_HEART_NAME {
            get {
                return ResourceManager.GetString("FULL_DIAMOND_HEART_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br&gt;The core is pulsing in the rate of your heart. Just having the pure diamond core near you, let you feel the pressure. It just needs the right vessel to hold it. ähnelt.
        /// </summary>
        internal static string SHELLLESS_DIAMOND_HEART_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHELLLESS_DIAMOND_HEART_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diamond Heart (Core) ähnelt.
        /// </summary>
        internal static string SHELLLESS_DIAMOND_HEART_NAME {
            get {
                return ResourceManager.GetString("SHELLLESS_DIAMOND_HEART_NAME", resourceCulture);
            }
        }
    }
}
