//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ElderbugDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElderbugDialog() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.ElderbugDialog", typeof(ElderbugDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have done it! You learned about everything in this world! Well… almost. There still are some knowledge bits that are not receivable yet. They say, that it may be accessable once the event &quot;Patch 2.1&quot; happens. Whatever that might be. Anyway, this kingdom is now yours. I have nothing to offer you anymore. I might consider leaving this place now… There are still some places elsewhere that are full of knowledge. ähnelt.
        /// </summary>
        internal static string Elderbug_All_Tasks_Done {
            get {
                return ResourceManager.GetString("Elderbug_All_Tasks_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this version of Hallownest I&apos;ve nothing left to offer to you. Good luck on your journey. ähnelt.
        /// </summary>
        internal static string Elderbug_Casual_Normal {
            get {
                return ResourceManager.GetString("Elderbug_Casual_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What an amusing twisted version of this land has been created. May you find your movement items early this run. Hehe... ähnelt.
        /// </summary>
        internal static string Elderbug_Casual_Rando {
            get {
                return ResourceManager.GetString("Elderbug_Casual_Rando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re a fan of changing your appearance it seems. Or maybe even changing the look of other things? ähnelt.
        /// </summary>
        internal static string Elderbug_CustomKnight {
            get {
                return ResourceManager.GetString("Elderbug_CustomKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh, I can sense the power that coursing through your shell. You managed to obtain a spell, congratulations. As an reward I&apos;ll teach you how to comprehent the knowledge written on the tablets. ähnelt.
        /// </summary>
        internal static string Elderbug_Done_Task_1 {
            get {
                return ResourceManager.GetString("Elderbug_Done_Task_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disappointed? Well I&apos;m sorry, but once &quot;Patch 2.1&quot; happen, there will be a conclusion to this story. Take care of yourself... ähnelt.
        /// </summary>
        internal static string Elderbug_End {
            get {
                return ResourceManager.GetString("Elderbug_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mh, but it seems like you&apos;ll have problems understanding the text and people of this world. I can teach you those skills, but since I don&apos;t want to waste time on a student which dies soon after learning, allow me to put you to a test first. ähnelt.
        /// </summary>
        internal static string Elderbug_Extra_Intro {
            get {
                return ResourceManager.GetString("Elderbug_Extra_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh, thank you very much. I haven&apos;t received such a kind hearted gift in years. I... just can&apos;t you leave without some kind of reward. Otherwise I&apos;d feel pretty bad. It is not much, but maybe this does help you. ähnelt.
        /// </summary>
        internal static string ELDERBUG_FLOWER_ACCEPT {
            get {
                return ResourceManager.GetString("ELDERBUG_FLOWER_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No? Oh what a shame. I hope you change you mind about that decision. I&apos;d really appreciate it. ähnelt.
        /// </summary>
        internal static string ELDERBUG_FLOWER_DECLINE {
            get {
                return ResourceManager.GetString("ELDERBUG_FLOWER_DECLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh! What a beautiful flower you have there. You know, I have a weakness for flowers. The always remind of the peaceful and happy things in life. I&apos;m sorry, if this is a bit rude, but may I have that one? ähnelt.
        /// </summary>
        internal static string ELDERBUG_FLOWER_REQUEST {
            get {
                return ResourceManager.GetString("ELDERBUG_FLOWER_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ah, you returned to me with this pretty flower. May I have it, this time? ähnelt.
        /// </summary>
        internal static string ELDERBUG_FLOWER_REREQUEST {
            get {
                return ResourceManager.GetString("ELDERBUG_FLOWER_REREQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seems like you achieved your first steps into the world of knowledge. I stand by my word of course. Take this. ähnelt.
        /// </summary>
        internal static string Elderbug_Gain_Listening {
            get {
                return ResourceManager.GetString("Elderbug_Gain_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greetings little knight! To come so far to defeat some kind of moth god creature, admirable indeed. Curious, how I&apos;m able to know about this? Well, let just say, the knowledge I acquired in my lifetime has allowed to me ascend even beyond the power of those &quot;Higher Beings&quot;. Although it might seem impossible to achieve for a small creature like you, it is quite the opposite. Not looking like a big threat may allow you to sneak your way into this kingdom and learning about it without being in danger of being  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Elderbug_Met {
            get {
                return ResourceManager.GetString("Elderbug_Met", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taking a normal adventure, I suppose? In this case, I don&apos;t have much to offer. Take this relic, this will allow you to control the wisdom of the kingdom. Remember &quot;Knowledge is Power&quot;. ähnelt.
        /// </summary>
        internal static string Elderbug_Normal {
            get {
                return ResourceManager.GetString("Elderbug_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re still too weak to be teached the language. Return to me once you obtained 5 different parts of knowledge. ähnelt.
        /// </summary>
        internal static string Elderbug_Not_Enough_Lore {
            get {
                return ResourceManager.GetString("Elderbug_Not_Enough_Lore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Want to know what I eat for breakfast? No? Then pick up the ability. Or do you really only want to talk with me and the snail shaman for the rest of your &quot;life&quot;? ähnelt.
        /// </summary>
        internal static string Elderbug_Not_Listening {
            get {
                return ResourceManager.GetString("Elderbug_Not_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t be shy, just pick it up. Mh? Did you expect me to actual teach you how to read this language? Oh silly you. Why waste time on learning such basic skills normally, when M A G I C does the trick. ähnelt.
        /// </summary>
        internal static string Elderbug_Not_Reading {
            get {
                return ResourceManager.GetString("Elderbug_Not_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t rush! I know that you thirsty for the lore, but take your time and pick up my reward first. It is a bit rude ignoring a self crafted present, isn&apos;t it? ähnelt.
        /// </summary>
        internal static string Elderbug_Pickup_Reminder {
            get {
                return ResourceManager.GetString("Elderbug_Pickup_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Going on a twisted adventure, I see. I&apos;ll still proceed as normal I suppose. ähnelt.
        /// </summary>
        internal static string Elderbug_Randomizer {
            get {
                return ResourceManager.GetString("Elderbug_Randomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die But it seems like that my inventory was unaffected by that. In that case, let me just give the artifact to control the obtained powers. Good luck with your Randomizer. Hehe... ähnelt.
        /// </summary>
        internal static string Elderbug_Randomizer_Not_Randomized {
            get {
                return ResourceManager.GetString("Elderbug_Randomizer_Not_Randomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A bit forgetful aren&apos;t we? Climb down the well and return to me with a spell. ähnelt.
        /// </summary>
        internal static string Elderbug_Remind_Task {
            get {
                return ResourceManager.GetString("Elderbug_Remind_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Below this well, you&apos;ll find the forgotten crossroads. Fight your way through it until you reach a creature of void. They will give you a powerful tool which helps you proceeding further into this kingdom. After you obtained it, return to me and I&apos;ll teach you how to read the tablet scattered around this place. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_1 {
            get {
                return ResourceManager.GetString("Elderbug_Task_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die So… much… POWER! You are so close to be called a &quot;Lore Master&quot;. Here two more scrolls to undo curses. Return to me with ALL 60 Powers obtained. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_10 {
            get {
                return ResourceManager.GetString("Elderbug_Task_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok, for your next task, gather the knowledge written on these tablets scattered around this kingdom and acquire their power. Note, that to allow some knowledge to be used outside of their normal area, you need to fully understand everything that culture has to offer. Return to me once you obtained 5 different parts of knowledge, then I&apos;ll teach you the language to interact with the bugs of this world. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_2 {
            get {
                return ResourceManager.GetString("Elderbug_Task_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doesn&apos;t it feel much better to be able to understand what others are talking about? I think so. Anyway, some bugs may offer you valuable knowledge as well. You should consider talking to anyone that you stumble across your journey. Come back to me after your obtained 10 powers total. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_3 {
            get {
                return ResourceManager.GetString("Elderbug_Task_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You slowly understand how valuable this knowledge is, do you? Take this old relic with you. It allows you to be aware of what knowledge you already understood. Return to me with a total of 15 powers. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_4 {
            get {
                return ResourceManager.GetString("Elderbug_Task_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some knowledge is placed very… unfortunate. For thoses cases, I&apos;ll allow you to use this. This scroll will allow my mind to share the knowledge about the tablet or bug which you touch on the relic. Be careful though, those scrolls can only be used once. Return to me with a total of 20 powers. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_5 {
            get {
                return ResourceManager.GetString("Elderbug_Task_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not all knowledge of this world is blessed. While I can&apos;t relieve a curse on you that easily, I at least can allow your artifact to seal unwanted powers. For this process you have to be in a calm state, on a bench maybe. Here apply this stone to your artifact. Return to me with a total of 30 powers, for even more. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_6 {
            get {
                return ResourceManager.GetString("Elderbug_Task_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are halfway done! Maybe some day I&apos;ll be able to call you &quot;Lore Master&quot; if you keep up that pace. Here is another scroll. This one may cleanse you from cursed knowledge you obtained if used. If there are no cursed pieces of wisdom in this kingdom, this will turn to geo instead. Anyway once you obtained 40 powers, return to me again. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_7 {
            get {
                return ResourceManager.GetString("Elderbug_Task_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How does it feel? Are you afraid of what you could do? Don&apos;t waste any thought on something like that. Gain even more knowledge. Let me see 50 powers coursing through you and then I&apos;ll reward you even more. ähnelt.
        /// </summary>
        internal static string Elderbug_Task_8 {
            get {
                return ResourceManager.GetString("Elderbug_Task_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incredible! With all this power, even Higher Beings are pitiful for someone like you, but don&apos;t stop now, you can achieve even more!. Take another scroll. Return to me with 55 powers total. You are on the path to ascend above all else! ähnelt.
        /// </summary>
        internal static string Elderbug_Task_9 {
            get {
                return ResourceManager.GetString("Elderbug_Task_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In a search for food, you have to adapt sometimes. Although I wouldn&apos;t recommend eating random mushrooms at all. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_BagOfMushrooms {
            get {
                return ResourceManager.GetString("Elderbug_Tip_BagOfMushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are some bugs that even I respect on a high level even though there knowledge is quite low. The Menderbugs of course! In this rotten corpse of a kingdom they still fulfill their duty with a smile. I&apos;d recommend not hurting them by the way. Else, I&apos;ll take care of you. What does that mean? Did you know that turning your save file to steel soul mode is incredibly easy? You figure out the rest... ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_BestMenderInTheWorld {
            get {
                return ResourceManager.GetString("Elderbug_Tip_BestMenderInTheWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I enjoyed fl... ehm walking through the city. Sure, the rain is annoying but there&apos;s a beautiful voice halling through the street. I sometimes wonder, what knowledge is hidden beyond this voice... ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_BlessingOfTheButterfly {
            get {
                return ResourceManager.GetString("Elderbug_Tip_BlessingOfTheButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The moss creatures of greenpath liked to hide tablets pointing towards the history of this area. I&apos;d take a closer look at the room with the moss knights. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_Camouflage {
            get {
                return ResourceManager.GetString("Elderbug_Tip_Camouflage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Being alone is a terrible feeling. In those cases some of us flee into their dreams to imagine a better life. So did this girl, before the left this city. But I think the infection got her at last. Poor girl, trapped inside the depth of the wastes, all alone. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_CaringShell {
            get {
                return ResourceManager.GetString("Elderbug_Tip_CaringShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a big caterpillar located within the ruins of this kingdom. This is a really old creature, which probably has gathered a lot of knowledge through his lifetime. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_ConcussiveStrike {
            get {
                return ResourceManager.GetString("Elderbug_Tip_ConcussiveStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I remember a banket with a lot of eggs which was served somewhere in the city. They disappeared fairly quickly though, though not because the bugs eat them quickly, rather because they were stolen by someone. I always suspected the theft fleed into the kitchen of the Bath House. I wonder if this is true... ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_DeliciousMeal {
            get {
                return ResourceManager.GetString("Elderbug_Tip_DeliciousMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is another adventure with a familiar looking mask traveling through this kingdom. He held some kind of glowing stone. Maybe you can catch up to him in the crystal peak? ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_DiamondCore {
            get {
                return ResourceManager.GetString("Elderbug_Tip_DiamondCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some cute girl climbed down this well not a long time ago. Considering that she wear a helmet and had a pickaxe, I&apos;d guess she walked to crystal peaks. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_DiamondDash {
            get {
                return ResourceManager.GetString("Elderbug_Tip_DiamondDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The pale king hides the secret of his actions somewhere in his palace. It would take a closer look at the walls there. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_DiminishingCurse {
            get {
                return ResourceManager.GetString("Elderbug_Tip_DiminishingCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighting with strenght? How pathetic, but it seems fitting with those weird bugs that go to the colosseum. Like this green caped guys, talking about some kind triforce that he need to collect... wait, did I mixed something up? ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_DramaticEntrance {
            get {
                return ResourceManager.GetString("Elderbug_Tip_DramaticEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A piece of knowledge is linked to the artifact of the Moth tribe. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_DreamBlessing {
            get {
                return ResourceManager.GetString("Elderbug_Tip_DreamBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you ignore his odor, the dung defender is pretty kind hearted and pleasant bug. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_EternalSentinel {
            get {
                return ResourceManager.GetString("Elderbug_Tip_EternalSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Although the Mantis of the Wastes define themselves through strength, you can&apos;t deny that they are certainly intelligent. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_EternalValor {
            get {
                return ResourceManager.GetString("Elderbug_Tip_EternalValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The bugs of the city always felt being watched. What fascinates me is that they always seemed so surprised once they learned that they truly have been watched. I mean, what do you expect if a bug titled &quot;The Watcher&quot; with a telescope is hiding inside a big tower? ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_EyeOfTheWatcher {
            get {
                return ResourceManager.GetString("Elderbug_Tip_EyeOfTheWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What a drama it had to be that one of the five knights had a relationship with a mantis. Did the father kill his own daughter after he found out? Who knows, that is another mystery which became forgotten in time. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_FlowerRing {
            get {
                return ResourceManager.GetString("Elderbug_Tip_FlowerRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It leaves me a bit confused that some creatures actual embraces the infection, especially the moss ones. Do you think the words the spoke are coming from Radiance herself or is the bug still talking through his own mind? ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_FollowTheLight {
            get {
                return ResourceManager.GetString("Elderbug_Tip_FollowTheLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you ask me, the jellyfishs seem a bit out of place. But Monomon seemed to like studying them. Maybe somewhere she has written down her notes. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_FriendOfTheJellyfish {
            get {
                return ResourceManager.GetString("Elderbug_Tip_FriendOfTheJellyfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From what I heard, the pilgrims where sometimes... a bit tedious to tolerate. I recall an incident where one pilgrim kicked a tablet enforcing the way of Unn, off the path. Let&apos;s just say... the pilgrim reached the city not in one piece. This happened somewhere above the Stone Sanctuary. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_GiftOfUnn {
            get {
                return ResourceManager.GetString("Elderbug_Tip_GiftOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imagine walking all the way down the pilgrim&apos;s path only to be held outside of the city with a gate. The life of a pilgrims seems hard sometimes. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_GloryOfTheWealth {
            get {
                return ResourceManager.GetString("Elderbug_Tip_GloryOfTheWealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The creatures of Greenpath were caution of the White Lady. The even put a warning in front of her territory. Well, before she arrived it was there area after all. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_GraspOfLife {
            get {
                return ResourceManager.GetString("Elderbug_Tip_GraspOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The is another lonely grave within the Garden of the Queen. I always wondered who could&apos;ve created that. Maybe the ghost of those who are buried there, might know the answer. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_GrassBombardement {
            get {
                return ResourceManager.GetString("Elderbug_Tip_GrassBombardement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did you walk by the temple below? They say within this giant egg is some kind of lore hidden. I know the truth, but since this is supposed to be the end of your journey, I&apos;ll tell no more. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_GreaterMind {
            get {
                return ResourceManager.GetString("Elderbug_Tip_GreaterMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some people assume that they stand above others just because of their appearance or wealth. Nothing comes close to the power knowledge offers. This woman... her ignorance made me sick. Should I...? No, stop thinking about it. Scorching the weak is not an option Elderbug... yet. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_HappyFate {
            get {
                return ResourceManager.GetString("Elderbug_Tip_HappyFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After the bugs moved through the big door into the city they needed to climb down to reach the streets. For a normal bug that seems highly dangerous. Maybe there is a warning sign or something hidden on the path? ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_HotStreak {
            get {
                return ResourceManager.GetString("Elderbug_Tip_HotStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A shared mind comes with many weaknesses and strengths. Personally, I prefer being on my own. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_Imposter {
            get {
                return ResourceManager.GetString("Elderbug_Tip_Imposter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Even in a society of spiders, they have someone is charge of helping birthing bug. I heard rumors that after the beast put herself to sleep, this creature moved down to from their village. You might want to take some kind of light source with you though. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_Infested {
            get {
                return ResourceManager.GetString("Elderbug_Tip_Infested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monomon had to write down some of her research somewhere. Maybe a closer look inside her archive can&apos;t hurt. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_JellyBelly {
            get {
                return ResourceManager.GetString("Elderbug_Tip_JellyBelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The owner of the archive Monomon was probably the most knowledgable bug in this entire kingdom. It is a shame that I didn&apos;t a chance to talk to her, before she became a dreamer. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_JellyfishFlow {
            get {
                return ResourceManager.GetString("Elderbug_Tip_JellyfishFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calling someone a heretic for studying this blue substance is very telling if you ask me. There is a reason why the king did that. Maybe he feared the power? A secret waiting for being revealed someday. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_JonisProtection {
            get {
                return ResourceManager.GetString("Elderbug_Tip_JonisProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Before you arrived here, there was some kind of annoying bug only talking about his 57 precepts. I know I said every bit of knowledge is important, but this case is an exception... ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_LaughableThreat {
            get {
                return ResourceManager.GetString("Elderbug_Tip_LaughableThreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are many damaged walls around this kingdom. Even behind something like that, a valuable tablet could be hidden. Taking a closer look at the Cliffs would be recommended. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_LifebloodOmen {
            get {
                return ResourceManager.GetString("Elderbug_Tip_LifebloodOmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The style of fighting from the mantis is impressive. Maybe I should start studying it, to expand my knowledge even more. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_MantisStyle {
            get {
                return ResourceManager.GetString("Elderbug_Tip_MantisStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are some posters talking about the beautiful Marissa somewhere in the city. You have to search EVERYWHERE for knowledge, even on something like that. Imagine some kind a bug hold its nail against your throat and will only let you leave if you can name the actress that is on stage today. Would you really want to be killed just because you only glanced over? I THINK NOT. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_MarissasAudience {
            get {
                return ResourceManager.GetString("Elderbug_Tip_MarissasAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Masks are truly fascinating, aren&apos;t they? You hide your true self and live on with some other identity. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_MaskOvercharge {
            get {
                return ResourceManager.GetString("Elderbug_Tip_MaskOvercharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This lifeblood substance even reached the top of Greenpath. I remember there being a tablet as well somewhere. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_MindblastOfUnn {
            get {
                return ResourceManager.GetString("Elderbug_Tip_MindblastOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The thorns in the wastes are not caused by the shrooms or the mantis but rather by the White Lady herself. You can see that yourself if you go to through the crossing point of those areas. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_OneOfUs {
            get {
                return ResourceManager.GetString("Elderbug_Tip_OneOfUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I heard rumors that the bugs of the soul sanctum have written some kind of &quot;Record Bela&quot;. After I searched through there with the annoying spell twisted on my back, I decided to take one of their computers and &quot;hack&quot; the text onto it. Hm? Don&apos;t ask me how, be real you are also annoyed about the representation in EVERY SINGLE MOVIE where this is a thing. Just imagine that, roll your eyes and proceed your journey. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_OverwhelmingPower {
            get {
                return ResourceManager.GetString("Elderbug_Tip_OverwhelmingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Mantis created some kind of thorn trials to practice their agility. But nowadays this area is flooded with the shrooms again. I&apos;d be curious of what the shroom say about destroying their biom to create such trials. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_PaleLuck {
            get {
                return ResourceManager.GetString("Elderbug_Tip_PaleLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The bugs of the soul sanctum had the right idea, but hiding in the city was there biggest mistake. Only the knowledge of all of Hallownest can defeat the infection. I mean, look at me. Am I infected? Of course not! ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_PureSpirit {
            get {
                return ResourceManager.GetString("Elderbug_Tip_PureSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knowledge of a higher being is interesting indeed. If you want to achieve your purpose who will stumble upon this knowledge anyway. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_QueenThorns {
            get {
                return ResourceManager.GetString("Elderbug_Tip_QueenThorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ugh, I can&apos;t stand for the flukes invading the waterways. Even if one of them is able to &quot;talk&quot;, there isn&apos;t much knowledge to gather. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_RelentlessSwarm {
            get {
                return ResourceManager.GetString("Elderbug_Tip_RelentlessSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I always wondered where the pilgrims came from. I thought mortal bugs would lose their mind once the left the bounds of this kingdom. The start of their journey is below in the crossroads somewhere. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_ReluctantPilgrim {
            get {
                return ResourceManager.GetString("Elderbug_Tip_ReluctantPilgrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did you know that when I arrived I had to bury the bug that normally buries the dead? Oh how ironic. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_Requiem {
            get {
                return ResourceManager.GetString("Elderbug_Tip_Requiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Look at the top of every room. Behind the grass and vines might be hidden knowledge. I wonder if this &quot;Shaw&quot; screaming creature just ignored it or didn&apos;t notice it. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_ReturnToUnn {
            get {
                return ResourceManager.GetString("Elderbug_Tip_ReturnToUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The knowledge of the truth that the Pale King sealed away has to be the most precious. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_SacredShell {
            get {
                return ResourceManager.GetString("Elderbug_Tip_SacredShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right before the big door leading to this town and the kingdom is a tablet written about obeying to the rules of this kingdom. Considering that you couldn&apos;t read at the time, it couldn&apos;t stop you, I suppose. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_ScrewTheRules {
            get {
                return ResourceManager.GetString("Elderbug_Tip_ScrewTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a hidden room somewhere in the white palace which holds the origin of the guards that you can find there. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_ShadowForged {
            get {
                return ResourceManager.GetString("Elderbug_Tip_ShadowForged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh the wisdom, so near the Pale King himself. I wonder if it was written by him. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_ShiningBound {
            get {
                return ResourceManager.GetString("Elderbug_Tip_ShiningBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hidden deep in the soul sanctum there is another record. Trust your feet and ehm.. ears to find it. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_SoulExtractEfficiency {
            get {
                return ResourceManager.GetString("Elderbug_Tip_SoulExtractEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personally, I&apos;d not take a stag to travel through this kingdom, even if I wouldn&apos;t be able to telep.. ehm running really quickly. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_StagAdoption {
            get {
                return ResourceManager.GetString("Elderbug_Tip_StagAdoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With so many thorns around I&apos;d think twice before proceeding to walk through Greenpath. But even there you&apos;d have to look for knowledge. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_TouchGrass {
            get {
                return ResourceManager.GetString("Elderbug_Tip_TouchGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Isn&apos;t it strange that the only mentioning of the Hollow Knight is at the fountain in the city? I mean, maybe this was intended to hide the sad truth behind it existence. Truly a tragedy... ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_Tourist {
            get {
                return ResourceManager.GetString("Elderbug_Tip_Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to admire the courage of the relic seeker that opened some kind of &quot;shop&quot; within a foreign city. I prefer staying up here for my sleep, much warmer and as a bonus you also stay dry. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_TreasureHunter {
            get {
                return ResourceManager.GetString("Elderbug_Tip_TreasureHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did you visit Leg Eater? Definitely an interesting creature isn&apos;t it. I wonder if the shrooms below whispered them something, that they became insane. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_UnitedWeStand {
            get {
                return ResourceManager.GetString("Elderbug_Tip_UnitedWeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep below the kingdom and even the palace there is a door which seals the truth of the king&apos;s actions. Before that, there might be a tablet telling about this. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_WeDontTalkAboutShade {
            get {
                return ResourceManager.GetString("Elderbug_Tip_WeDontTalkAboutShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On the path where you took your first steps into this kingdom, there might be some kind of tablet. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_WellFocused {
            get {
                return ResourceManager.GetString("Elderbug_Tip_WellFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Under the mushrooms there is a special one which some tablet talks about. Even if this tablet is hidden beyond the bounds of a normal bug of this kingdom, for someone like you this shouldn&apos;t be a problem though. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_WisdomOfTheSage {
            get {
                return ResourceManager.GetString("Elderbug_Tip_WisdomOfTheSage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The bees of the hive have isoleted themself from the rest of the kingdom. This didn&apos;t prevent me from entering their domain though. Maybe you should visit them, too. ähnelt.
        /// </summary>
        internal static string Elderbug_Tip_YouLikeJazz {
            get {
                return ResourceManager.GetString("Elderbug_Tip_YouLikeJazz", resourceCulture);
            }
        }
    }
}
