//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerDescriptions() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.PowerDescriptions", typeof(PowerDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows you to pick a mushroom to consume each 180 seconds. White shroom: Increases the speed of the game by 40%. Yellow shroom: Generates 20 soul each second, but causes nausea. Red shroom: Gives you 4 extra health, heals you fully and increases your nail damage by 20%, but you can&apos;t dash. Green shroom: Makes you small, decrease the gravity by 50% and doubles all damage taken. Taking the same mushroom twice in a row nerfs it&apos;s positive effect by 50%. Taking the same mushroom three times in a row, deals 2 da [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BagOfMushrooms {
            get {
                return ResourceManager.GetString("BagOfMushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wings now deal 12 damage upon contact with enemy and apply massive knockback downwards. While your double jump is on cooldown, instead of taking damage from enemies below you, you deal 4 damage, regain soul and jump automatically again. (This does not restore wings) ähnelt.
        /// </summary>
        internal static string BlessingOfTheButterfly {
            get {
                return ResourceManager.GetString("BlessingOfTheButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After standing still for 5 seconds, you gain invincibility until you do something. If you are wearing Shape of Unn, you keep the invincibility while focusing and moving as a slug. ähnelt.
        /// </summary>
        internal static string Camouflage {
            get {
                return ResourceManager.GetString("Camouflage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enviroment hazards (like spikes) don&apos;t deal damage to you anymore. ähnelt.
        /// </summary>
        internal static string CaringShell {
            get {
                return ResourceManager.GetString("CaringShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Great Slash and Dash Slash cause Concussion on their target for 3 seconds. Concussed enemies take 10% more damage from nail attacks and increase their knockback by 50% (66% of Heavy Blow). Nail hits on the target extend the duration by 0.5 seconds each. Cyclone Slash is not counted as a nail slash in this case. Also cause enemies to glance 50% of their hits, decreasing their damage by 1. ähnelt.
        /// </summary>
        internal static string ConcussiveStrike {
            get {
                return ResourceManager.GetString("ConcussiveStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can consume a rancid egg to heal you for 1 mask every 8 seconds and gain a +20% damage buff for 3 minutes. Press jump to consume the egg. ähnelt.
        /// </summary>
        internal static string DeliciousMeal {
            get {
                return ResourceManager.GetString("DeliciousMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crystal Heart snares all enemies in the room if you hit a wall. The duration of the stun and cdash damage increases with the c dash duration. (Stun duration is capped at 10 seconds, gain 5 damage and 10% speed per second, gain invincibility after 3 seconds.) ähnelt.
        /// </summary>
        internal static string DiamondCore {
            get {
                return ResourceManager.GetString("DiamondCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crystal Heart is cast 0.3 seconds faster and can be hold midair while pressing up. Doubled, if you have Diamond Core unlocked. Drains 20 Soul per second (or 10 if you have Diamond Core). ähnelt.
        /// </summary>
        internal static string DiamondDash {
            get {
                return ResourceManager.GetString("DiamondDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you take 10 hits, you will no longer count as overcharmed, resets if you sit on a bench. The UI only updates if you open the charm screen. ähnelt.
        /// </summary>
        internal static string DiminishingCurse {
            get {
                return ResourceManager.GetString("DiminishingCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defeated Dreamers grant the dream nail an additional effect (doubled with awoken dreamnail).&lt;br&gt;Lurien: Roots the target for 3 seconds (15 seconds cooldown)&lt;br&gt;Herrah: Spawn 2 weavers. &lt;br&gt;Monomon: Per 100 Essence you have a 1% chance to instant kill the enemy (capped at 175 damage). Capped at 2400 Essence for 24%. ähnelt.
        /// </summary>
        internal static string DreamBlessing {
            get {
                return ResourceManager.GetString("DreamBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When entering a new room marks a random enemy with a red outline. If you kill that enemy FIRST another one gets marked. If all enemies are killed in the right order you receive a soul vessel fragment, mask shard, charm notch, 200 geo, or a small damage buff. ähnelt.
        /// </summary>
        internal static string ElderbugHitList {
            get {
                return ResourceManager.GetString("ElderbugHitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defender&apos;s Crest clouds are 150% bigger and tick twice as fast. Baldur shell now takes seven hits instead of four (ten with defender&apos;s Crest. When getting hit, while baldur shell is up, you gain 15 soul if you are also wearing Defender&apos;s Crest. ähnelt.
        /// </summary>
        internal static string EternalSentinel {
            get {
                return ResourceManager.GetString("EternalSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Each 12 hits on enemies, heal you for 1 mask. Not hitting an enemy for 3 seconds will take away a stack each half of a second. ähnelt.
        /// </summary>
        internal static string EternalValor {
            get {
                return ResourceManager.GetString("EternalValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grants the lantern effect. If you already have the lantern effect and would take lethal damage, you will be healed to full hp instead (with Joni&apos;s you gaining 5 lifeblood instead). Once triggered, has to be restored by looking through the telescope by lurien. ähnelt.
        /// </summary>
        internal static string EyeOfTheWatcher {
            get {
                return ResourceManager.GetString("EyeOfTheWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase the damage of your nail arts by 10% for each recipient for the flower. ähnelt.
        /// </summary>
        internal static string FlowerRing {
            get {
                return ResourceManager.GetString("FlowerRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you hold left while casting dreamnail, it will spawn an orange portal by your side, which you can travel to from anywhere in the room (Requires dream gate to work). Hold right while casting dreamnail to warp to the portal. Warping will consume 1 essence and the portal. Neither get&apos;s consumed if you have awoken Dreamnail (the portal will swap position with you instead). ähnelt.
        /// </summary>
        internal static string FollowTheLight {
            get {
                return ResourceManager.GetString("FollowTheLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re immune to jellyfishs enemies and explosions. Note: Non Jellyfish explosion enemies, &quot;could&quot; still deal 2 damage on contact. You&apos;re just immune to the explosion itself. ähnelt.
        /// </summary>
        internal static string FriendOfTheJellyfish {
            get {
                return ResourceManager.GetString("FriendOfTheJellyfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gain the shape of Unn effect for focusing. If you&apos;re wearing Shape of Unn, focus restores 15 soul on a successful cast. ähnelt.
        /// </summary>
        internal static string GiftOfUnn {
            get {
                return ResourceManager.GetString("GiftOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies drop double geo. Press Quick Map + Up to become invincible. For each second this is active it drains 1 more geo. Press Quick Map + Down to cancel the effect (or leave the room). While the effect is inactive the cost decrease by 1 each 5 second (or each 2.5 seconds if you have Fragile/Unbreakable Greed equipped). ähnelt.
        /// </summary>
        internal static string GloryOfTheWealth {
            get {
                return ResourceManager.GetString("GloryOfTheWealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While running on the ground spawn a grass patch each second. Every 10th one is &quot;pale grass&quot; which, upon destroying, causes all other spawned grass by you to cast wraith that deal 10 damage (20 if shape of unn is equipped). Grass despawns after 10 seconds. ähnelt.
        /// </summary>
        internal static string GraspOfLife {
            get {
                return ResourceManager.GetString("GraspOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pressing left while casting. spawns a bomb which explodes after 3 seconds, that deals 40 damage (60 with shaman stone) and breaks damaged walls/ground. Pressing right, will consum a lifeblood mask to spawn a more powerful bomb, with a bigger radius, 50 % more damage and the ability to break ALL damaged floors/walls in the room, even heavy floors and one way walls. ähnelt.
        /// </summary>
        internal static string GrassBombardement {
            get {
                return ResourceManager.GetString("GrassBombardement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activates the tracker, to show you how many powers you are missing. If the counter is green, you have global access to the power in the area. ähnelt.
        /// </summary>
        internal static string GreaterMind {
            get {
                return ResourceManager.GetString("GreaterMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After sitting on a bench, your nail damage, nail range, running speed, dash speed and cdash charge up speed is increased. You also gain 1 soul per second. ähnelt.
        /// </summary>
        internal static string HappyFate {
            get {
                return ResourceManager.GetString("HappyFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When hitting an enemy with the nail, increases it&apos;s damage by 1 (max. 3 stacks per nail upgrade (15 total)). Resets if you don&apos;t hit an enemy. ähnelt.
        /// </summary>
        internal static string HotStreak {
            get {
                return ResourceManager.GetString("HotStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While wearing spore shrooms, focus has a 20% chance to add a lifeblood (doesn&apos;t work if you have 3 or more lifeblood). ähnelt.
        /// </summary>
        internal static string Imposter {
            get {
                return ResourceManager.GetString("Imposter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hitting an enemy with the nail plants an egg to the enemy (Capped at 5), which spawns a weaver once the enemy died. Weavers also apply eggs (Capped at 25). Weavers despawn after 20 seconds or upon leaving the room. ähnelt.
        /// </summary>
        internal static string Infested {
            get {
                return ResourceManager.GetString("Infested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease your falling speed by about 20% and triples the time needed in air, for a hard fall. ähnelt.
        /// </summary>
        internal static string JellyBelly {
            get {
                return ResourceManager.GetString("JellyBelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You swim 4 times as fast. ähnelt.
        /// </summary>
        internal static string JellyfishFlow {
            get {
                return ResourceManager.GetString("JellyfishFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When going to another area, you will be granted 5 life blood (10 if you have Joni&apos;s equipped). Each 3 seconds a lifeblood will fade away. ähnelt.
        /// </summary>
        internal static string JonisProtection {
            get {
                return ResourceManager.GetString("JonisProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawns a grimmkin every 180 seconds. Killing the ghost grants 3/6/9 lifeblood (based on ghost level). The ghost disappears if you leave the room or if 90 seconds passed. The chances for the ghost adjust based on your current nail level. I&apos;ll will not list the chances here. Look at the repository, if you want to know. ähnelt.
        /// </summary>
        internal static string LifebloodOmen {
            get {
                return ResourceManager.GetString("LifebloodOmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase your nail range by 50% (from base). ähnelt.
        /// </summary>
        internal static string MantisStyle {
            get {
                return ResourceManager.GetString("MantisStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After 45 to 120 seconds spawn multiple companions (Weavers, Hatchlings, Grimmchilds) that persist in the current room or for 30 to 90 seconds. If Marissa is dead, spawns Revek each 45 to 120 seconds, that persist in the current room or 20 to 90 seconds. ähnelt.
        /// </summary>
        internal static string MarissasAudience {
            get {
                return ResourceManager.GetString("MarissasAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overcharge one of your mask (it glows in different colors), while you have exactly that much health, a circle gathers around you that deal damage and restore 8 soul each second. The overcharged mask changes every 30 seconds and may never select the full hp mask. Inactive while you have Joni&apos;s Blessing equipped. ähnelt.
        /// </summary>
        internal static string MaskOvercharge {
            get {
                return ResourceManager.GetString("MaskOvercharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hitting an enemy with the dream nail permanently increases the taken damage by 2. Bonus for wearing charm: +1 Dreamwielder, +2 Dreamshield and +3 Shape of Unn. The effect is doubled with awoken dream nail. ähnelt.
        /// </summary>
        internal static string MindblastOfUnn {
            get {
                return ResourceManager.GetString("MindblastOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every twelve seconds you cast the deep focus spore cloud. Hold the crystal dash button to prevent that (in case you want to do pogos for example). ähnelt.
        /// </summary>
        internal static string OneOfUs {
            get {
                return ResourceManager.GetString("OneOfUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you cast a spell while your soul vessel is full (not counting additional soul vessels), they deal twice as much damage and are twice as big. ähnelt.
        /// </summary>
        internal static string OverwhelmingPower {
            get {
                return ResourceManager.GetString("OverwhelmingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you would take damage, you have a 2% chance to be healed instead. Increased by 4% for each King&apos;s Brand and Kingssoul. Also increased by 1 % for each king&apos;s idol you have. ähnelt.
        /// </summary>
        internal static string PaleLuck {
            get {
                return ResourceManager.GetString("PaleLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you have 0 soul after casting a spell you will gain an rotating orb around you that deals 5 contact damage. If you have 3 orbs active, the next fireball will increase their size, let them explode upon contact for 20 damage and restore 10 soul. Soul Snatcher and Soul Eater will increase the soul gained by the orb. Shaman Stone will increase the orb explosion damage. ähnelt.
        /// </summary>
        internal static string PureSpirit {
            get {
                return ResourceManager.GetString("PureSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thorns of Agony are now &quot;Queen Thorns&quot;, which removes the freeze on hit. restore soul if it hits an enemy and has a 33% chance to restore 1 hp if it kills an enemy. ähnelt.
        /// </summary>
        internal static string QueenThorns {
            get {
                return ResourceManager.GetString("QueenThorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hits with flukes restore 2 soul, or 5 if the enemy died. ähnelt.
        /// </summary>
        internal static string RelentlessSwarm {
            get {
                return ResourceManager.GetString("RelentlessSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While standing of the ground, the grubberfly elegy effect is active regardless of your hp (Joni conditions are still normal). If you have grubberfly equipped, the damage on ground is doubled instead. Also mutes the beams after a few casts. ähnelt.
        /// </summary>
        internal static string ReluctantPilgrim {
            get {
                return ResourceManager.GetString("ReluctantPilgrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holding focus, while you dying will spawn you in dirtmouth instead of your bench. Holding dream nail will spawn you at spirit&apos;s glade instead (when the glade is open). Holding Crystal Dash will spawn you at Hallownests Crown (?), requires Crystal Heart to work. ähnelt.
        /// </summary>
        internal static string Requiem {
            get {
                return ResourceManager.GetString("Requiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Movement speed is increased by 3 and your dash cooldown is reduces by 0.5 seconds, while you facing left. ähnelt.
        /// </summary>
        internal static string ReturnToUnn {
            get {
                return ResourceManager.GetString("ReturnToUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can longer take more than one damage per hit (excluding overcharmed). ähnelt.
        /// </summary>
        internal static string SacredShell {
            get {
                return ResourceManager.GetString("SacredShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fury of the Fallen is now also active with 2 hp, but the damage buff is decreased to 50%. Grubberfly Beams are only nerfed by 40%. ähnelt.
        /// </summary>
        internal static string ScrewTheRules {
            get {
                return ResourceManager.GetString("ScrewTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease the cooldown of shade cloak by 0.2 seconds and increases sharp shadow damage by 100%. ähnelt.
        /// </summary>
        internal static string ShadowForged {
            get {
                return ResourceManager.GetString("ShadowForged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For each charm you&apos;re wearing, you gain 1 soul per 2 seconds. ähnelt.
        /// </summary>
        internal static string ShiningBound {
            get {
                return ResourceManager.GetString("ShiningBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You gain 5 more soul per hit on enemies and your extra soul vessel soul will be added instantly to be used for spells after casting spell. This does NOT affect focus, unless you do the wind up again. ähnelt.
        /// </summary>
        internal static string SoulExtractEfficiency {
            get {
                return ResourceManager.GetString("SoulExtractEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every 8 seconds standing on grass, you heal 1 mask. Decreased to 4 seconds if wearing Shape of Unn. ähnelt.
        /// </summary>
        internal static string TouchGrass {
            get {
                return ResourceManager.GetString("TouchGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can talk to the firefly to the right to teleport to black egg temple for 50 geo, or back to this room from the temple. ähnelt.
        /// </summary>
        internal static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While your shade is active, you deal 30% more damage and increase your nail length by 25%. The effects are doubled, if you are in the same room as your shade. ähnelt.
        /// </summary>
        internal static string TrueForm {
            get {
                return ResourceManager.GetString("TrueForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weavers are bigger, Grimmchild shoots faster and Hatchling deal more damage for each companion (of those three) you have. ähnelt.
        /// </summary>
        internal static string UnitedWeStand {
            get {
                return ResourceManager.GetString("UnitedWeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t get the soul limit punishment, when dying. Your geo will still be on the shade. When dying while the shade is active, your shade only loose 50% of your geo. ähnelt.
        /// </summary>
        internal static string WeDontTalkAboutTheShade {
            get {
                return ResourceManager.GetString("WeDontTalkAboutTheShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus is cast 30% faster. ähnelt.
        /// </summary>
        internal static string WellFocused {
            get {
                return ResourceManager.GetString("WellFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For each Mr. Mushroom stage that you completed, spells cost 1 soul less. ähnelt.
        /// </summary>
        internal static string WisdomOfTheSage {
            get {
                return ResourceManager.GetString("WisdomOfTheSage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can now have 10 hatchlings at a time, they spawn twice at fast and cost only 25% of their normal soul. ähnelt.
        /// </summary>
        internal static string YouLikeJazz {
            get {
                return ResourceManager.GetString("YouLikeJazz", resourceCulture);
            }
        }
    }
}
