//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerHints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerHints() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.PowerHints", typeof(PowerHints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows you to consume a yummy mushroom snack occasionly. The saturation may power you up. Caution: Can cause throw up if you eat too much of the same ones. Press quick map to select another and cdash + dash to consume the mushroom. ähnelt.
        /// </summary>
        internal static string BagOfMushrooms {
            get {
                return ResourceManager.GetString("BagOfMushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The best day of Menderbug lifes occured! He asked Mender Berri out and she said yes! Together, they made the signs of this kingdom even better. They even hide some reward for the good souls that let them have work to do. ähnelt.
        /// </summary>
        internal static string BestMenderInTheWorld {
            get {
                return ResourceManager.GetString("BestMenderInTheWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Wings have received the blessing of the butterfly, which allows them to crush enemies beneath them and repel even higher. While the wings rest on you, your enemies shall be shattered by your feet. From your best girl (besides Myla) c: ähnelt.
        /// </summary>
        internal static string BlessingOfTheButterfly {
            get {
                return ResourceManager.GetString("BlessingOfTheButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While doing nothing, your mind slowly ascent to Unn&apos;s dream, while your shell is shielded by Unn&apos;s power. ähnelt.
        /// </summary>
        internal static string Camouflage {
            get {
                return ResourceManager.GetString("Camouflage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No hazard shall cast harm onto you... UwU ähnelt.
        /// </summary>
        internal static string CaringShell {
            get {
                return ResourceManager.GetString("CaringShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your huge nail swings cause Concussion on their target, which will cause the target to suffer more from your nail and extend the concussion. ähnelt.
        /// </summary>
        internal static string ConcussiveStrike {
            get {
                return ResourceManager.GetString("ConcussiveStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can now consume the &quot;delicious&quot; eggs to provide you a temporarily saturation effect to make your nail stronger and regenerate your wounds. Press jump on the egg in the inventory to consume the egg. ähnelt.
        /// </summary>
        internal static string DeliciousMeal {
            get {
                return ResourceManager.GetString("DeliciousMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The crystal heart&apos;s core absorbed the power of diamond and got even stronger. If you hit a wall, all foes may be stunned shortly. The power of the diamond increases over time, makes you unstoppable once you got enough power. ähnelt.
        /// </summary>
        internal static string DiamondCore {
            get {
                return ResourceManager.GetString("DiamondCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The shell of crystal heart is powered with the might of diamonds, which causes a quicker energie cast and allows you to stop you mid air. Hold up to remain at your position. Drains souls rapidly. ähnelt.
        /// </summary>
        internal static string DiamondDash {
            get {
                return ResourceManager.GetString("DiamondDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you suffer from the curse of greed, it will vanish once you experienced enough pain after resting. ähnelt.
        /// </summary>
        internal static string DiminishingCurse {
            get {
                return ResourceManager.GetString("DiminishingCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Staying up against a powerful foe will restore all your power for a glorious fight. ähnelt.
        /// </summary>
        internal static string DramaticEntrance {
            get {
                return ResourceManager.GetString("DramaticEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The dream artifact uses the power it absorbs from their powerful victims to use it&apos;s hidden power.&lt;br&gt;Monomon: Through her knowledge she exposes the foes biggest weakness.&lt;br&gt;Lurien: His gaze may freeze the enemy in place.&lt;br&gt;Herrah: Invoking her children from the victim. ähnelt.
        /// </summary>
        internal static string DreamBlessing {
            get {
                return ResourceManager.GetString("DreamBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When entering a new room with enemies the list marks enemies. If you succeed the \&quot;talk\&quot; with them, you are granted a reward. Be careful, elderbug demands a clean execution. ähnelt.
        /// </summary>
        internal static string ElderbugHitList {
            get {
                return ResourceManager.GetString("ElderbugHitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases your scent while wearing the sign of the protector. The shield of the ancient ones is more resistent and gather soul with the blessing of the protector. ähnelt.
        /// </summary>
        internal static string EternalSentinel {
            get {
                return ResourceManager.GetString("EternalSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The heat of the battle shall allow you to endure more pain. ähnelt.
        /// </summary>
        internal static string EternalValor {
            get {
                return ResourceManager.GetString("EternalValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The eye of the watcher will protect you and share it&apos;s sight, allowing you to see in the dark. If the eye can fully see you, it gaze may once prevent a fatal blow on you. To call the eye again, look through the tool of the watcher. ähnelt.
        /// </summary>
        internal static string EyeOfTheWatcher {
            get {
                return ResourceManager.GetString("EyeOfTheWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The power of all existing flower are gathered if you channel powerful strikes. ähnelt.
        /// </summary>
        internal static string FlowerRing {
            get {
                return ResourceManager.GetString("FlowerRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows you to weave with the pure essence of light to form a portal which you can travel to. Moving to far away will destroy the unstable portal. Hold left while swinging the artifact of the light to weave the portal and hold right to travel through it. As long as the artifact has not its full potential, travelling will consume the energy of the dreams and destroy the portal once entered. If not, the portal will remain at your entry point. (Requires dream gate to work) ähnelt.
        /// </summary>
        internal static string FollowTheLight {
            get {
                return ResourceManager.GetString("FollowTheLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jellyfishs and explosions may no longer harm you. ähnelt.
        /// </summary>
        internal static string FriendOfTheJellyfish {
            get {
                return ResourceManager.GetString("FriendOfTheJellyfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grants you the power of Unn. ähnelt.
        /// </summary>
        internal static string GiftOfUnn {
            get {
                return ResourceManager.GetString("GiftOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your enemies may &quot;share&quot; more of their wealth with you. Your wealth may protect you from the hits of those peasants... for a fee of course. Press Quick Map + Up to activate the effect and Quick Map + Down to cancel the effect. (In case you forget this input combination, the effect also deactivates itself once the leave the room). The cost increase fast over time while the effect is active and slowly decrease once inactive. If you are really greedy, the cost decrease faster. The great civilians of Hallownest [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GloryOfTheWealth {
            get {
                return ResourceManager.GetString("GloryOfTheWealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While running on the ground, the breath of life shall grow grass below your feet. Sometimes, a pale blessed one may appear instead. Killing it, shall let your hear the cheers of the normal one. ähnelt.
        /// </summary>
        internal static string GraspOfLife {
            get {
                return ResourceManager.GetString("GraspOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forms the grass in Hallownest with the power of the soul to a &quot;special delivery&quot; which explodes shortly after creation, dealing huge damage. The disruption may break loose walls and floors. Requires soul to construct the bomb. Press (Quick)cast and left to drop the bomb. They say, that you also can channel the blue plague, to create an even stronger bomb which can even break the heaviest stones and emits a destruction shockwave through the room. Press (Quick)cast and right to consume the blue blood and spaw [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GrassBombardement {
            get {
                return ResourceManager.GetString("GrassBombardement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can now sense, which knowledge of the world you&apos;re missing. (Look in the mod menu for more options.) ähnelt.
        /// </summary>
        internal static string GreaterMind {
            get {
                return ResourceManager.GetString("GreaterMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your &quot;happiness&quot; increases all your abilities slightly. Getting hit makes you sad. :c A good rest may restore your hapiness. ähnelt.
        /// </summary>
        internal static string HappyFate {
            get {
                return ResourceManager.GetString("HappyFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully striking enemies shall increase your power. The power will fade away from your weapon if it doesn&apos;t hit a foe. ähnelt.
        /// </summary>
        internal static string HotStreak {
            get {
                return ResourceManager.GetString("HotStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While being part of the shrooms, sometime you focus treacherous energys... AMOGUS ähnelt.
        /// </summary>
        internal static string Imposter {
            get {
                return ResourceManager.GetString("Imposter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plant spider eggs in the wounds of your victims, that burst open on death. ähnelt.
        /// </summary>
        internal static string Infested {
            get {
                return ResourceManager.GetString("Infested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are feeling light, like a feather. ähnelt.
        /// </summary>
        internal static string JellyBelly {
            get {
                return ResourceManager.GetString("JellyBelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;ve gained the swimming agility of the jellyfishs... And you are now a part of the jellyspotters! ähnelt.
        /// </summary>
        internal static string JellyfishFlow {
            get {
                return ResourceManager.GetString("JellyfishFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When going to a new area, you will receive the gift of Joni, which will quickly fade away. ähnelt.
        /// </summary>
        internal static string JonisProtection {
            get {
                return ResourceManager.GetString("JonisProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can you hear it? Those pesky peasant laugh about you behind your back. They don&apos;t even consider you a real threat to them. Oh they will learn to respect you, once you swung your nail at one of them. ähnelt.
        /// </summary>
        internal static string LaughableThreat {
            get {
                return ResourceManager.GetString("LaughableThreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sometimes you will be haunted by a ghost from a distant land. Killing it will grant you the essence of it&apos;s soul. A more powerful weapon may attract more powerful foes. ähnelt.
        /// </summary>
        internal static string LifebloodOmen {
            get {
                return ResourceManager.GetString("LifebloodOmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your weapon may reach further away foes. ähnelt.
        /// </summary>
        internal static string MantisStyle {
            get {
                return ResourceManager.GetString("MantisStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While Marissa sings on stage, occasionally spawns a crowd that helps you. If you killed her however... you will be haunted by her biggest fan. ähnelt.
        /// </summary>
        internal static string MarissasAudience {
            get {
                return ResourceManager.GetString("MarissasAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Let one your mask occasionly overcharge. If it is the one that protects you, it emits a searing circle, that also absorbs the loose soul around you. ähnelt.
        /// </summary>
        internal static string MaskOvercharge {
            get {
                return ResourceManager.GetString("MaskOvercharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your dream nail emits the power of Unn to the target&apos;s mind, which causes their bodies to be more vulnerable. ähnelt.
        /// </summary>
        internal static string MindblastOfUnn {
            get {
                return ResourceManager.GetString("MindblastOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occasionally you emit a spore cloud. (Hold the super dash button to prevent the cloud.) ähnelt.
        /// </summary>
        internal static string OneOfUs {
            get {
                return ResourceManager.GetString("OneOfUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Casting spells with full capacity will grant your spell much more power. Be careful though, these spells are  so powerful that you can easily loose control of them, searing your vessel and shatter your soul. It will take some time to recover your soul. ähnelt.
        /// </summary>
        internal static string OverwhelmingPower {
            get {
                return ResourceManager.GetString("OverwhelmingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When someone casts harm on you, sometimes you are blessed by the higher being instead. Especially if you have some artefacts related to him. ähnelt.
        /// </summary>
        internal static string PaleLuck {
            get {
                return ResourceManager.GetString("PaleLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Using the last resort of your soul will purify it&apos;s vessel and spawn an orb out of pure light. If you channeled three orbs, they will follow your powerful spell and detonate upon contact, returning their gathered soul to you. ähnelt.
        /// </summary>
        internal static string PureSpirit {
            get {
                return ResourceManager.GetString("PureSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The thorns of agony have received the blessing of the queen. ähnelt.
        /// </summary>
        internal static string QueenThorns {
            get {
                return ResourceManager.GetString("QueenThorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flukes rip the soul out of there victims. ähnelt.
        /// </summary>
        internal static string RelentlessSwarm {
            get {
                return ResourceManager.GetString("RelentlessSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While you stay on the path, your nail shall receive the gift of the grubfather. ähnelt.
        /// </summary>
        internal static string ReluctantPilgrim {
            get {
                return ResourceManager.GetString("ReluctantPilgrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When your shell breaks, holding a pure focus may arise you at the home of death. Holding the light&apos;s artifact will instead catch you in the protecting wings of the last one, if she opened her secret. Holding the shiny stone vessel, will drop your soul onto the now abandoned place, where the light started its revenge. ähnelt.
        /// </summary>
        internal static string Requiem {
            get {
                return ResourceManager.GetString("Requiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reject Bugness, return to Slug. You move faster to Unn. ähnelt.
        /// </summary>
        internal static string ReturnToUnn {
            get {
                return ResourceManager.GetString("ReturnToUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infuse your shell with the pale power of the monarch which grants you tenacity against strong strikes. ähnelt.
        /// </summary>
        internal static string SacredShell {
            get {
                return ResourceManager.GetString("SacredShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your rage is weaker but grows quicker. ähnelt.
        /// </summary>
        internal static string ScrewTheRules {
            get {
                return ResourceManager.GetString("ScrewTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The void energy return quicker to you. ähnelt.
        /// </summary>
        internal static string ShadowForged {
            get {
                return ResourceManager.GetString("ShadowForged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every magic relic you currently wearing  shall gather more soul for you. ähnelt.
        /// </summary>
        internal static string ShiningBound {
            get {
                return ResourceManager.GetString("ShiningBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows you to drain soul more efficient from your foes and draw you reserve more quickly. ähnelt.
        /// </summary>
        internal static string SoulExtractEfficiency {
            get {
                return ResourceManager.GetString("SoulExtractEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small scared stags want a good home. Take this egg with you and care for it. Touching it a bit tougher, may hatch it instantly and allow you to help the stag fulfill their purpose. After setting it free and waiting a bit a new one may appear here. ähnelt.
        /// </summary>
        internal static string StagAdoption {
            get {
                return ResourceManager.GetString("StagAdoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The flora may nourish your shell, if you stand long enough near it. ähnelt.
        /// </summary>
        internal static string TouchGrass {
            get {
                return ResourceManager.GetString("TouchGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Want to see the incredible black egg temple? Talk to the firefly to the right. Drinks are not included in the price. Also offers back travel. ähnelt.
        /// </summary>
        internal static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revealing the buried treasures of the kingdom, may give you their effect and the favor of the relic seeker. ähnelt.
        /// </summary>
        internal static string TreasureHunter {
            get {
                return ResourceManager.GetString("TreasureHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While the true form is revealed, its vessels nail gets more powerful. Especially near your true self. ähnelt.
        /// </summary>
        internal static string TrueForm {
            get {
                return ResourceManager.GetString("TrueForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your companions inspire each other. ähnelt.
        /// </summary>
        internal static string UnitedWeStand {
            get {
                return ResourceManager.GetString("UnitedWeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shade? What should that be? Can you prove, that the &quot;Shade&quot; exist? Your soul vessel and geo? What are you talking about? ähnelt.
        /// </summary>
        internal static string WeDontTalkAboutShade {
            get {
                return ResourceManager.GetString("WeDontTalkAboutShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You gain pure focus faster. ähnelt.
        /// </summary>
        internal static string WellFocused {
            get {
                return ResourceManager.GetString("WellFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guide the Sage through his journey to learn how to use your spells more efficient. ähnelt.
        /// </summary>
        internal static string WisdomOfTheSage {
            get {
                return ResourceManager.GetString("WisdomOfTheSage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your hatchlings hatch way more aggressive and don&apos;t need that much soul to grow. ähnelt.
        /// </summary>
        internal static string YouLikeJazz {
            get {
                return ResourceManager.GetString("YouLikeJazz", resourceCulture);
            }
        }
    }
}
