//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerKeys() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.PowerKeys", typeof(PowerKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIRAFFE_MEET ähnelt.
        /// </summary>
        internal static string BagOfMushroomsPower {
            get {
                return ResourceManager.GetString("BagOfMushroomsPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MENDER_DIARY ähnelt.
        /// </summary>
        internal static string BestMenderInTheWorldPower {
            get {
                return ResourceManager.GetString("BestMenderInTheWorldPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MARISSA_TALK ähnelt.
        /// </summary>
        internal static string BlessingOfTheButterflyPower {
            get {
                return ResourceManager.GetString("BlessingOfTheButterflyPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GREEN_TABLET_05 ähnelt.
        /// </summary>
        internal static string CamouflagePower {
            get {
                return ResourceManager.GetString("CamouflagePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BRETTA_RESCUE_3 ähnelt.
        /// </summary>
        internal static string CaringShellPower {
            get {
                return ResourceManager.GetString("CaringShellPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIGCAT_TALK_01 ähnelt.
        /// </summary>
        internal static string ConcussiveStrikePower {
            get {
                return ResourceManager.GetString("ConcussiveStrikePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die POGGY_TALK ähnelt.
        /// </summary>
        internal static string DeliciousMealPower {
            get {
                return ResourceManager.GetString("DeliciousMealPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die QUIRREL_MINES_1 ähnelt.
        /// </summary>
        internal static string DiamondCorePower {
            get {
                return ResourceManager.GetString("DiamondCorePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MINER_MEET_1_B ähnelt.
        /// </summary>
        internal static string DiamondDashPower {
            get {
                return ResourceManager.GetString("DiamondDashPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLAQUE_WARN ähnelt.
        /// </summary>
        internal static string DiminishingCursePower {
            get {
                return ResourceManager.GetString("DiminishingCursePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TISO_BENCH_GREET ähnelt.
        /// </summary>
        internal static string DramaticEntrancePower {
            get {
                return ResourceManager.GetString("DramaticEntrancePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DREAMERS_INSPECT_RG5 ähnelt.
        /// </summary>
        internal static string DreamBlessingPower {
            get {
                return ResourceManager.GetString("DreamBlessingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DUNG_DEF_SIGN ähnelt.
        /// </summary>
        internal static string EternalSentinelPower {
            get {
                return ResourceManager.GetString("EternalSentinelPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MANTIS_PLAQUE_02 ähnelt.
        /// </summary>
        internal static string EternalValorPower {
            get {
                return ResourceManager.GetString("EternalValorPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LURIAN_JOURNAL ähnelt.
        /// </summary>
        internal static string EyeOfTheWatcherPower {
            get {
                return ResourceManager.GetString("EyeOfTheWatcherPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XUN_GRAVE_INSPECT ähnelt.
        /// </summary>
        internal static string FlowerRingPower {
            get {
                return ResourceManager.GetString("FlowerRingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MOSS_CULTIST_01 ähnelt.
        /// </summary>
        internal static string FollowTheLightPower {
            get {
                return ResourceManager.GetString("FollowTheLightPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ARCHIVE_01 ähnelt.
        /// </summary>
        internal static string FriendOfTheJellyfishPower {
            get {
                return ResourceManager.GetString("FriendOfTheJellyfishPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GREEN_TABLET_02 ähnelt.
        /// </summary>
        internal static string GiftOfUnnPower {
            get {
                return ResourceManager.GetString("GiftOfUnnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PILGRIM_TAB_02 ähnelt.
        /// </summary>
        internal static string GloryOfTheWealthPower {
            get {
                return ResourceManager.GetString("GloryOfTheWealthPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GREEN_TABLET_07 ähnelt.
        /// </summary>
        internal static string GraspOfLifePower {
            get {
                return ResourceManager.GetString("GraspOfLifePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COMPLETION_RATE_UNLOCKED ähnelt.
        /// </summary>
        internal static string GreaterMindPower {
            get {
                return ResourceManager.GetString("GreaterMindPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EMILITIA_MEET ähnelt.
        /// </summary>
        internal static string HappyFatePower {
            get {
                return ResourceManager.GetString("HappyFatePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RUIN_TAB_01 ähnelt.
        /// </summary>
        internal static string HotStreakPower {
            get {
                return ResourceManager.GetString("HotStreakPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FUNG_TAB_02 ähnelt.
        /// </summary>
        internal static string ImposterPower {
            get {
                return ResourceManager.GetString("ImposterPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPIDER_MEET ähnelt.
        /// </summary>
        internal static string InfestedPower {
            get {
                return ResourceManager.GetString("InfestedPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ARCHIVE_02 ähnelt.
        /// </summary>
        internal static string JellyBellyPower {
            get {
                return ResourceManager.GetString("JellyBellyPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ARCHIVE_03 ähnelt.
        /// </summary>
        internal static string JellyfishFlowPower {
            get {
                return ResourceManager.GetString("JellyfishFlowPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JONI_TALK ähnelt.
        /// </summary>
        internal static string JonisProtectionPower {
            get {
                return ResourceManager.GetString("JonisProtectionPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZOTE_DEEPNEST_1 ähnelt.
        /// </summary>
        internal static string LaughableThreatPower {
            get {
                return ResourceManager.GetString("LaughableThreatPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CLIFF_TAB_02 ähnelt.
        /// </summary>
        internal static string LifebloodOmenPower {
            get {
                return ResourceManager.GetString("LifebloodOmenPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MANTIS_PLAQUE_01 ähnelt.
        /// </summary>
        internal static string MantisStylePower {
            get {
                return ResourceManager.GetString("MantisStylePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RUINS_MARISSA_POSTER ähnelt.
        /// </summary>
        internal static string MarissasAudiencePower {
            get {
                return ResourceManager.GetString("MarissasAudiencePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MASK_MAKER_GREET ähnelt.
        /// </summary>
        internal static string MaskOverchargePower {
            get {
                return ResourceManager.GetString("MaskOverchargePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GREEN_TABLET_03 ähnelt.
        /// </summary>
        internal static string MindblastOfUnnPower {
            get {
                return ResourceManager.GetString("MindblastOfUnnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FUNG_TAB_04 ähnelt.
        /// </summary>
        internal static string OneOfUsPower {
            get {
                return ResourceManager.GetString("OneOfUsPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAGE_COMP_02 ähnelt.
        /// </summary>
        internal static string OverwhelmingPowerPower {
            get {
                return ResourceManager.GetString("OverwhelmingPowerPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FUNG_TAB_01 ähnelt.
        /// </summary>
        internal static string PaleLuckPower {
            get {
                return ResourceManager.GetString("PaleLuckPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAGE_COMP_03 ähnelt.
        /// </summary>
        internal static string PureSpiritPower {
            get {
                return ResourceManager.GetString("PureSpiritPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die QUEEN_MEET ähnelt.
        /// </summary>
        internal static string QueenThornsPower {
            get {
                return ResourceManager.GetString("QueenThornsPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FLUKE_HERMIT_IDLE_1 ähnelt.
        /// </summary>
        internal static string RelentlessSwarmPower {
            get {
                return ResourceManager.GetString("RelentlessSwarmPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PILGRIM_TAB_01 ähnelt.
        /// </summary>
        internal static string ReluctantPilgrimPower {
            get {
                return ResourceManager.GetString("ReluctantPilgrimPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GRAVEDIGGER_TALK ähnelt.
        /// </summary>
        internal static string RequiemPower {
            get {
                return ResourceManager.GetString("RequiemPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GREEN_TABLET_06 ähnelt.
        /// </summary>
        internal static string ReturnToUnnPower {
            get {
                return ResourceManager.GetString("ReturnToUnnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NONE ähnelt.
        /// </summary>
        internal static string SacredShellPower {
            get {
                return ResourceManager.GetString("SacredShellPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TUT_TAB_02 ähnelt.
        /// </summary>
        internal static string ScrewTheRulesPower {
            get {
                return ResourceManager.GetString("ScrewTheRulesPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WP_WORKSHOP_01 ähnelt.
        /// </summary>
        internal static string ShadowForgedPower {
            get {
                return ResourceManager.GetString("ShadowForgedPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WP_THRONE_01 ähnelt.
        /// </summary>
        internal static string ShiningBoundPower {
            get {
                return ResourceManager.GetString("ShiningBoundPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAGE_COMP_01 ähnelt.
        /// </summary>
        internal static string SoulExtractEfficiencyPower {
            get {
                return ResourceManager.GetString("SoulExtractEfficiencyPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STAG_EGG_INSPECT ähnelt.
        /// </summary>
        internal static string StagAdoptionPower {
            get {
                return ResourceManager.GetString("StagAdoptionPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GREEN_TABLET_01 ähnelt.
        /// </summary>
        internal static string TouchGrassPower {
            get {
                return ResourceManager.GetString("TouchGrassPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FOUNTAIN_PLAQUE_DESC ähnelt.
        /// </summary>
        internal static string TouristPower {
            get {
                return ResourceManager.GetString("TouristPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TUT_TAB_03 ähnelt.
        /// </summary>
        internal static string TrueFormPower {
            get {
                return ResourceManager.GetString("TrueFormPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FUNG_TAB_03 ähnelt.
        /// </summary>
        internal static string UnitedWeStandPower {
            get {
                return ResourceManager.GetString("UnitedWeStandPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABYSS_TUT_TAB_01 ähnelt.
        /// </summary>
        internal static string WeDontTalkAboutShadePower {
            get {
                return ResourceManager.GetString("WeDontTalkAboutShadePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TUT_TAB_01 ähnelt.
        /// </summary>
        internal static string WellFocusedPower {
            get {
                return ResourceManager.GetString("WellFocusedPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MR_MUSH_RIDDLE_TAB_NORMAL ähnelt.
        /// </summary>
        internal static string WisdomOfTheSagePower {
            get {
                return ResourceManager.GetString("WisdomOfTheSagePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HIVEQUEEN_TALK ähnelt.
        /// </summary>
        internal static string YouLikeJazzPower {
            get {
                return ResourceManager.GetString("YouLikeJazzPower", resourceCulture);
            }
        }
    }
}
