//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShopDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShopDescriptions() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.ShopDescriptions", typeof(ShopDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some caterpillar guy told me this, maybe you can comprehent what this means. ähnelt.
        /// </summary>
        internal static string Bardoon {
            get {
                return ResourceManager.GetString("Bardoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is a diary which I found on the street, seems to belong to some girl... No ehm, I didn&apos;t read it. ähnelt.
        /// </summary>
        internal static string Bretta_Diary {
            get {
                return ResourceManager.GetString("Bretta_Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Isn&apos;t she a very brave girl? Fear her roar! ähnelt.
        /// </summary>
        internal static string Cloth {
            get {
                return ResourceManager.GetString("Cloth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This tells the story of the sacrifice of the dreamers. ähnelt.
        /// </summary>
        internal static string Dreamer_Tablet {
            get {
                return ResourceManager.GetString("Dreamer_Tablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It&apos;s a gift with an extraordinary smell. ähnelt.
        /// </summary>
        internal static string Dung_Defender {
            get {
                return ResourceManager.GetString("Dung_Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The mantis buried him even after he attacked them. How nice of them. ähnelt.
        /// </summary>
        internal static string Elder_Hu {
            get {
                return ResourceManager.GetString("Elder_Hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Just take it quick before she wants this back. She will probably pay 1000 times the amount it&apos;s worth. Nobody should think, she couldn&apos;t afford this, right? ähnelt.
        /// </summary>
        internal static string Emilitia {
            get {
                return ResourceManager.GetString("Emilitia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The words spoken by the child of the A L L U R I N G mother ähnelt.
        /// </summary>
        internal static string Fluke_Hermit {
            get {
                return ResourceManager.GetString("Fluke_Hermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was no sign, that said, that I couldn&apos;t take this with me. At least, no sign I could read. ähnelt.
        /// </summary>
        internal static string Fountain {
            get {
                return ResourceManager.GetString("Fountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something from an idiot who thought it would be a good idea to an area full a beasts. And then he died... \&quot;Insert Surprised Pikachu Meme here\&quot;&quot; ähnelt.
        /// </summary>
        internal static string Galien {
            get {
                return ResourceManager.GetString("Galien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They found their god, in this shop. Not talking about you, of course. ähnelt.
        /// </summary>
        internal static string Godseeker {
            get {
                return ResourceManager.GetString("Godseeker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It&apos;s gorbin time! (to ascent!) (with Gorb) 
        ///- Gorb ähnelt.
        /// </summary>
        internal static string Gorb {
            get {
                return ResourceManager.GetString("Gorb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Considering that these live in the garden, being an arsonist might not be the best for them. ähnelt.
        /// </summary>
        internal static string Grasshopper {
            get {
                return ResourceManager.GetString("Grasshopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You might be thinking: Can&apos;t I just go outside and talk to him myself? Hey, if people buy water bottles, it was worth a shot. ähnelt.
        /// </summary>
        internal static string Gravedigger {
            get {
                return ResourceManager.GetString("Gravedigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last words spoken by the heretic. Should probably cost more than 1000. Buy it now, before I change my mind. ähnelt.
        /// </summary>
        internal static string Joni {
            get {
                return ResourceManager.GetString("Joni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I didn&apos;t took this from the door... it fell to the ground and I decided I&apos;d return it to him... later. ähnelt.
        /// </summary>
        internal static string Lemm_Sign {
            get {
                return ResourceManager.GetString("Lemm_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From the most beautiful voice of the world besides me. ähnelt.
        /// </summary>
        internal static string Marissa {
            get {
                return ResourceManager.GetString("Marissa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did the shade gate exists before he went in? If so, HOW could&apos;ve he pass that? Is Markoth void? O.o ähnelt.
        /// </summary>
        internal static string Markoth {
            get {
                return ResourceManager.GetString("Markoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say the lore master creator hates this damn *****. Whatever that means. ähnelt.
        /// </summary>
        internal static string Marmu {
            get {
                return ResourceManager.GetString("Marmu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From the creator of all those masks, these words shall extend your knowledge of the world. ähnelt.
        /// </summary>
        internal static string Mask_Maker {
            get {
                return ResourceManager.GetString("Mask_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menderbug allowed me to take a look at their diary. What a kind heart bug. YOU&apos;LL BE SORRY IF YOU TRY TO KILL THEM! ähnelt.
        /// </summary>
        internal static string Menderbug_Diary {
            get {
                return ResourceManager.GetString("Menderbug_Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please just take this... I don&apos;t want this in my shop anymore... ähnelt.
        /// </summary>
        internal static string Midwife {
            get {
                return ResourceManager.GetString("Midwife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I&apos;m not sure about this... just take it away. ähnelt.
        /// </summary>
        internal static string Moss_Prophet {
            get {
                return ResourceManager.GetString("Moss_Prophet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From the best girl in hallownest. Don&apos;t even dare, to hurt her... ähnelt.
        /// </summary>
        internal static string Myla {
            get {
                return ResourceManager.GetString("Myla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I wonder what her name was before she... you know. If that&apos;s her real name, that is just asking for something to rip out your eyes. ähnelt.
        /// </summary>
        internal static string No_Eyes {
            get {
                return ResourceManager.GetString("No_Eyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Want to know a secret? I&apos;ve no clue who Poggy is. ähnelt.
        /// </summary>
        internal static string Poggy {
            get {
                return ResourceManager.GetString("Poggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The queen sent this through the kingdom for the day, someone like you arrives. How do I know? Well... don&apos;t ask. ähnelt.
        /// </summary>
        internal static string Queen {
            get {
                return ResourceManager.GetString("Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The wisdom of a real adventurer, which can swim fairly good. :) ähnelt.
        /// </summary>
        internal static string Quirrel {
            get {
                return ResourceManager.GetString("Quirrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A special lore tablet, which was hidden deep in Soul Sanctum. ähnelt.
        /// </summary>
        internal static string Record_Bela {
            get {
                return ResourceManager.GetString("Record_Bela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My thoughts on a stag egg I found. ähnelt.
        /// </summary>
        internal static string Stag_Egg {
            get {
                return ResourceManager.GetString("Stag_Egg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brooding Mawlek offered me this. I&apos;m not sure what this could mean... ähnelt.
        /// </summary>
        internal static string Tiso {
            get {
                return ResourceManager.GetString("Tiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why are gravestones so damn expensive? Well the inscription isn&apos;t at least. ähnelt.
        /// </summary>
        internal static string Traitor_Grave {
            get {
                return ResourceManager.GetString("Traitor_Grave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A queen from a distant land tortured me with this. Let me share my pain with you. ähnelt.
        /// </summary>
        internal static string Vespa {
            get {
                return ResourceManager.GetString("Vespa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die As a bug, I&apos;d be scared of eating unknown mushrooms. ähnelt.
        /// </summary>
        internal static string Willoh {
            get {
                return ResourceManager.GetString("Willoh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The words of the king, for what happens with traitors. ähnelt.
        /// </summary>
        internal static string Xero {
            get {
                return ResourceManager.GetString("Xero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ugh... ähnelt.
        /// </summary>
        internal static string Zote {
            get {
                return ResourceManager.GetString("Zote", resourceCulture);
            }
        }
    }
}
