//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TreasureHunter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TreasureHunter() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.TreasureHunter", typeof(TreasureHunter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seems like an order for charts from Cornifer. Maybe his wife will allow you to take the charts in his name after showing her this? ähnelt.
        /// </summary>
        internal static string Shop_Desc_Special_Treasure_0 {
            get {
                return ResourceManager.GetString("Shop_Desc_Special_Treasure_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A journal that was buried deep within the kingdom. The only thing that you can read on this is &quot;Silksong Release Date&quot;. What could that be? ähnelt.
        /// </summary>
        internal static string Shop_Desc_Special_Treasure_1 {
            get {
                return ResourceManager.GetString("Shop_Desc_Special_Treasure_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A special seal alloyed in silver, to make it look more shiny. But since it was buried below dirt, it did lose most of it. ähnelt.
        /// </summary>
        internal static string Shop_Desc_Special_Treasure_2 {
            get {
                return ResourceManager.GetString("Shop_Desc_Special_Treasure_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A King&apos;s Idol forged in bronze, opposed to all other greyish relics related to the Pale King, which does seem odd. ähnelt.
        /// </summary>
        internal static string Shop_Desc_Special_Treasure_3 {
            get {
                return ResourceManager.GetString("Shop_Desc_Special_Treasure_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An arcane egg crafted with pure gold. It emits some threating aura... somehow. ähnelt.
        /// </summary>
        internal static string Shop_Desc_Special_Treasure_4 {
            get {
                return ResourceManager.GetString("Shop_Desc_Special_Treasure_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A special key, once in the possession of the Pale King. Legend say, that he could use this to open (almost) every lock in the entire kingdom. ähnelt.
        /// </summary>
        internal static string Shop_Desc_Special_Treasure_5 {
            get {
                return ResourceManager.GetString("Shop_Desc_Special_Treasure_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The highest award a member of the moth tribe could receive. It is said, that those who are wielding this amulet can catch dreams of others more easily. ähnelt.
        /// </summary>
        internal static string Shop_Desc_Special_Treasure_6 {
            get {
                return ResourceManager.GetString("Shop_Desc_Special_Treasure_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lemm&apos;s Order ähnelt.
        /// </summary>
        internal static string Shop_Title_Special_Treasure_0 {
            get {
                return ResourceManager.GetString("Shop_Title_Special_Treasure_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silksong Journal ähnelt.
        /// </summary>
        internal static string Shop_Title_Special_Treasure_1 {
            get {
                return ResourceManager.GetString("Shop_Title_Special_Treasure_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silver Hallownest Seal ähnelt.
        /// </summary>
        internal static string Shop_Title_Special_Treasure_2 {
            get {
                return ResourceManager.GetString("Shop_Title_Special_Treasure_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bronze King&apos;s Idol ähnelt.
        /// </summary>
        internal static string Shop_Title_Special_Treasure_3 {
            get {
                return ResourceManager.GetString("Shop_Title_Special_Treasure_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Golden Arcane Egg ähnelt.
        /// </summary>
        internal static string Shop_Title_Special_Treasure_4 {
            get {
                return ResourceManager.GetString("Shop_Title_Special_Treasure_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magic Key ähnelt.
        /// </summary>
        internal static string Shop_Title_Special_Treasure_5 {
            get {
                return ResourceManager.GetString("Shop_Title_Special_Treasure_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dream Medallion ähnelt.
        /// </summary>
        internal static string Shop_Title_Special_Treasure_6 {
            get {
                return ResourceManager.GetString("Shop_Title_Special_Treasure_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A golden version of an arcane egg? Oh, how exceptional! If this contains secret knowledge from the ancient civilization that lived here before Hallownest? I&apos;m honestly very excited to look into this. If you can bring me more arcane eggs, even normal ones, I&apos;ll add a huge amount of geo for your service. Why I still give you just 500 for this? Well... what is that behind you? ähnelt.
        /// </summary>
        internal static string SoldEgg {
            get {
                return ResourceManager.GetString("SoldEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ugh, what is that? A bronze version of the idols? Why would you do this? This does look rather unpleasant. Maybe it was the first of it&apos;s kind or something? Oh, in that case... that would make a set with this much more valuable and interesting. If I can figure out why the first one would be bronze that would open a whole lot history left forgotten... ähnelt.
        /// </summary>
        internal static string SoldIdol {
            get {
                return ResourceManager.GetString("SoldIdol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interesting, it seems like this a special kind of journal. It depicts some kind of date, but only a small part of it... Ah wait a moment, I think I&apos;ve seen those patterns before. Yeah, on the other journals scattered around this kingdom. If I can assemble them all, maybe I&apos;ll be able to tell when this mysterious &quot;Silksong&quot; may occur. Listen up, these journals are now way more valueable to me then before, which means I&apos;m down to pay way more for them. Additionally for bringing me the main piece, let me give  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SoldJournal {
            get {
                return ResourceManager.GetString("SoldJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This seal does seem special. It is little bit larger than the other ones and covered in a silver shell. But over the time it seems that it has lost its shiny appearance, what a shame. Anyway let me give you a small reward for bringing me this. You know what, I&apos;m willing to pay even more for those relics. There must something special about them, especially now that I see this. I&apos;ll give these a closer look... ähnelt.
        /// </summary>
        internal static string SoldSeal {
            get {
                return ResourceManager.GetString("SoldSeal", resourceCulture);
            }
        }
    }
}
