//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TwistedPowerDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwistedPowerDescriptions() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreMaster.Properties.TwistedPowerDescriptions", typeof(TwistedPowerDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every 30 to 300 seconds activate the camera effect (or speed up effect, if the yellow mushroom got disabled) from the yellow shroom. ähnelt.
        /// </summary>
        internal static string BagOfMushrooms {
            get {
                return ResourceManager.GetString("BagOfMushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destroying signs and some background objects take 50 geo from you. If you have no geo, you take 1 damage instead. ähnelt.
        /// </summary>
        internal static string BestMenderInTheWorld {
            get {
                return ResourceManager.GetString("BestMenderInTheWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monarch wings take 3 seconds to recharge, regardless if refreshed earlier. Doesn&apos;t refresh wings after these three seconds! ähnelt.
        /// </summary>
        internal static string BlessingOfTheButterfly {
            get {
                return ResourceManager.GetString("BlessingOfTheButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The knight is invisible. ähnelt.
        /// </summary>
        internal static string Camouflage {
            get {
                return ResourceManager.GetString("Camouflage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hazard respawns zone don&apos;t work. You always spawn at the start of the room. ähnelt.
        /// </summary>
        internal static string CaringShell {
            get {
                return ResourceManager.GetString("CaringShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting hit cause concussion on you, inverting left/right inputs during it&apos;s duration. Last 3 seconds. Taking a hit while already being concussed, extends the duration by 2 seconds. ähnelt.
        /// </summary>
        internal static string ConcussiveStrike {
            get {
                return ResourceManager.GetString("ConcussiveStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poggy is chasing you, eating/killing you after 2 minutes past. You can feed him rancid eggs from the inventory to reset the timer to 2 mins. ähnelt.
        /// </summary>
        internal static string DeliciousMeal {
            get {
                return ResourceManager.GetString("DeliciousMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can no longer cancel crystal dash unless being hit by an enemy or charging into a wall. ähnelt.
        /// </summary>
        internal static string DiamondCore {
            get {
                return ResourceManager.GetString("DiamondCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crystal Dash takes 0.6 seconds longer to charge up. ähnelt.
        /// </summary>
        internal static string DiamondDash {
            get {
                return ResourceManager.GetString("DiamondDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charms cost 1 notch more. ähnelt.
        /// </summary>
        internal static string DiminishingCurse {
            get {
                return ResourceManager.GetString("DiminishingCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entering a boss fight, sets your health to 1 and clears you soul. ähnelt.
        /// </summary>
        internal static string DramaticEntrance {
            get {
                return ResourceManager.GetString("DramaticEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dream Nail only gives you 10 soul (+ 5 for every dreamer) doubled with dream wielder. Also dream nail is cast 50% slower. ähnelt.
        /// </summary>
        internal static string DreamBlessing {
            get {
                return ResourceManager.GetString("DreamBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When entering a new room with enemies the list marks enemies. If you succeed the \&quot;talk\&quot; with them, you are granted a reward. Be careful, elderbug demands a clean execution. ähnelt.
        /// </summary>
        internal static string ElderbugHitList {
            get {
                return ResourceManager.GetString("ElderbugHitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dung clouds no longer deal damage and stays 10 seconds instead of 1. Wearing defender&apos;s crest does decrease the duration to 5 seconds instead. ähnelt.
        /// </summary>
        internal static string EternalSentinel {
            get {
                return ResourceManager.GetString("EternalSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hitting an enemy does generate a stack up to 24. After not hitting an enemy for 3 seconds a stack will go away each 1 second. If enemies you damaged, are still alive once all stacks ran out, you take 2 damage. ähnelt.
        /// </summary>
        internal static string EternalValor {
            get {
                return ResourceManager.GetString("EternalValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All rooms are 1 stage darker. ähnelt.
        /// </summary>
        internal static string EyeOfTheWatcher {
            get {
                return ResourceManager.GetString("EyeOfTheWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only use nail arts with a delicant flower. ähnelt.
        /// </summary>
        internal static string FlowerRing {
            get {
                return ResourceManager.GetString("FlowerRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Casting dream nail costs 2 essence (1 with awoken dream nail). ähnelt.
        /// </summary>
        internal static string FollowTheLight {
            get {
                return ResourceManager.GetString("FollowTheLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jellyfishs spawn all over Hallownest. ähnelt.
        /// </summary>
        internal static string FriendOfTheJellyfish {
            get {
                return ResourceManager.GetString("FriendOfTheJellyfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focusing takes 66 soul. While you have Shape of Unn equipped, this effect is negated. ähnelt.
        /// </summary>
        internal static string GiftOfUnn {
            get {
                return ResourceManager.GetString("GiftOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies that drop geo normally, only drop 1. ähnelt.
        /// </summary>
        internal static string GloryOfTheWealth {
            get {
                return ResourceManager.GetString("GloryOfTheWealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Walking on the ground for 2 seconds, spawn a fool eater under you. ähnelt.
        /// </summary>
        internal static string GraspOfLife {
            get {
                return ResourceManager.GetString("GraspOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every 7 to 14 jump spawns a grass bomb behind you. ähnelt.
        /// </summary>
        internal static string GrassBombardement {
            get {
                return ResourceManager.GetString("GrassBombardement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After you die, you lose the last obtained lore power. ähnelt.
        /// </summary>
        internal static string GreaterMind {
            get {
                return ResourceManager.GetString("GreaterMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease your walk- and walkspeed by 0.2, nail damage by 1 and increase your dash cooldown by 0.2 every time you get hit (up to 10 total). Resets once you sit on a bench. ähnelt.
        /// </summary>
        internal static string HappyFate {
            get {
                return ResourceManager.GetString("HappyFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your nail does deal 1 damage. Increasing by 1 each time you hit an enemy (up to 3 per nail upgrade). Resetting if you don&apos;t hit an enemy with the nail. ähnelt.
        /// </summary>
        internal static string HotStreak {
            get {
                return ResourceManager.GetString("HotStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus has a 20% to not restore health. Reduces to 10% if you wear spore shroom. ähnelt.
        /// </summary>
        internal static string Imposter {
            get {
                return ResourceManager.GetString("Imposter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawns a red spider wave every 7 seconds. The last wave spawns a big unkillable one. Resets upon changing the room. ähnelt.
        /// </summary>
        internal static string Infested {
            get {
                return ResourceManager.GetString("Infested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The time you need to be in the air for hard fall is decreased to 0.5 seconds. ähnelt.
        /// </summary>
        internal static string JellyBelly {
            get {
                return ResourceManager.GetString("JellyBelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot move in water. ähnelt.
        /// </summary>
        internal static string JellyfishFlow {
            get {
                return ResourceManager.GetString("JellyfishFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot obtain lifeblood. Besides charms... probably? ähnelt.
        /// </summary>
        internal static string JonisProtection {
            get {
                return ResourceManager.GetString("JonisProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some enemies are alerted immediatly after entering the room. ähnelt.
        /// </summary>
        internal static string LaughableThreat {
            get {
                return ResourceManager.GetString("LaughableThreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawns a grimmkin every 3 minutes, blocking all exits until it is killed. ähnelt.
        /// </summary>
        internal static string LifebloodOmen {
            get {
                return ResourceManager.GetString("LifebloodOmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease your nail size by 0.6. ähnelt.
        /// </summary>
        internal static string MantisStyle {
            get {
                return ResourceManager.GetString("MantisStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occassionaly spawns revek chasing you for 20 to 90 seconds. ähnelt.
        /// </summary>
        internal static string MarissasAudience {
            get {
                return ResourceManager.GetString("MarissasAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you are not on the blinking mask, you loose soul rapidly. ähnelt.
        /// </summary>
        internal static string MaskOvercharge {
            get {
                return ResourceManager.GetString("MaskOvercharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies cannot be hit until you dream nail them. If you don&apos;t have dream nail all enemies have triple their health. ähnelt.
        /// </summary>
        internal static string MindblastOfUnn {
            get {
                return ResourceManager.GetString("MindblastOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawns a spore cloud every 12 second. Staying in the cloud for 2 seconds lets you take 1 damage. ähnelt.
        /// </summary>
        internal static string OneOfUs {
            get {
                return ResourceManager.GetString("OneOfUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Casting spells while you don&apos;t have full soul (doesn&apos;t affect extra soul vessel) only deal 1 damage. ähnelt.
        /// </summary>
        internal static string OverwhelmingPower {
            get {
                return ResourceManager.GetString("OverwhelmingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies have a 5% of being healed instead if you hit them with your nail. ähnelt.
        /// </summary>
        internal static string PaleLuck {
            get {
                return ResourceManager.GetString("PaleLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spells always take your entire soul. ähnelt.
        /// </summary>
        internal static string PureSpirit {
            get {
                return ResourceManager.GetString("PureSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thorns of Agony are always active, but without the hitbox to damage enemy. ähnelt.
        /// </summary>
        internal static string QueenThorns {
            get {
                return ResourceManager.GetString("QueenThorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vengeful Spirit/Shadesoul is replaced by 1 fluke. Wearing fluke nest increases the amount of flukes by 3. ähnelt.
        /// </summary>
        internal static string RelentlessSwarm {
            get {
                return ResourceManager.GetString("RelentlessSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only attack in the air if you have 1 or full health. ähnelt.
        /// </summary>
        internal static string ReluctantPilgrim {
            get {
                return ResourceManager.GetString("ReluctantPilgrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After dying, you always spawn in Dirtmouth ähnelt.
        /// </summary>
        internal static string Requiem {
            get {
                return ResourceManager.GetString("Requiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re slowly drawn to the left. ähnelt.
        /// </summary>
        internal static string ReturnToUnn {
            get {
                return ResourceManager.GetString("ReturnToUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You take double damage from all sources of damage. ähnelt.
        /// </summary>
        internal static string SacredShell {
            get {
                return ResourceManager.GetString("SacredShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You deal less damage based on your health amount. Also fury of the fallen doesn&apos;t work. ähnelt.
        /// </summary>
        internal static string ScrewTheRules {
            get {
                return ResourceManager.GetString("ScrewTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shade cloak cooldown is increased by 0.4 seconds. ähnelt.
        /// </summary>
        internal static string ShadowForged {
            get {
                return ResourceManager.GetString("ShadowForged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charms do not work. ähnelt.
        /// </summary>
        internal static string ShiningBound {
            get {
                return ResourceManager.GetString("ShiningBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You gain 5 less soul from hits on enemy. Also looses 1 soul every second. ähnelt.
        /// </summary>
        internal static string SoulExtractEfficiency {
            get {
                return ResourceManager.GetString("SoulExtractEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The destination of a stag travel is randomly chosen. Only chooses opened stag stations + Stag Nest (with a 5% chance). ähnelt.
        /// </summary>
        internal static string StagAdoption {
            get {
                return ResourceManager.GetString("StagAdoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standing near grass takes a mask every 1.5 seconds. ähnelt.
        /// </summary>
        internal static string TouchGrass {
            get {
                return ResourceManager.GetString("TouchGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entering the black egg costs 3000. ähnelt.
        /// </summary>
        internal static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lemm only pays half for relics. ähnelt.
        /// </summary>
        internal static string TreasureHunter {
            get {
                return ResourceManager.GetString("TreasureHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawns a shade every 2 minutes, taking all your geo and fleeing to the exit where you entered from. The shade can fly through walls. After reaching the exit it stays 5 seconds there. After the time expires it vanishes with all geo that it had hold on. ähnelt.
        /// </summary>
        internal static string TrueForm {
            get {
                return ResourceManager.GetString("TrueForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For every companion you have, grimmchild shoot slower, weavers are smaller and hatchlings deal less damage. ähnelt.
        /// </summary>
        internal static string UnitedWeStand {
            get {
                return ResourceManager.GetString("UnitedWeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every enemy spawns a sibling upon death. Even with void heart, it stays aggressive. ähnelt.
        /// </summary>
        internal static string WeDontTalkAboutShade {
            get {
                return ResourceManager.GetString("WeDontTalkAboutShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus is cast 30% slower. ähnelt.
        /// </summary>
        internal static string WellFocused {
            get {
                return ResourceManager.GetString("WellFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spells cost 2 soul more for every Mr. Mushroom stage that you haven&apos;t visited yet. ähnelt.
        /// </summary>
        internal static string WisdomOfTheSage {
            get {
                return ResourceManager.GetString("WisdomOfTheSage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hatchlings spawn regardless if you have Glowing Womb equipped. Hatchlings take 15 souls instead of 8. ähnelt.
        /// </summary>
        internal static string YouLikeJazz {
            get {
                return ResourceManager.GetString("YouLikeJazz", resourceCulture);
            }
        }
    }
}
